#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatDongSan.Models.QLSuatAn
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HRTV")]
	public partial class QLSuatAnDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_HT_MaVach(tbl_HT_MaVach instance);
    partial void Updatetbl_HT_MaVach(tbl_HT_MaVach instance);
    partial void Deletetbl_HT_MaVach(tbl_HT_MaVach instance);
    partial void Inserttbl_SA_PhieuAn(tbl_SA_PhieuAn instance);
    partial void Updatetbl_SA_PhieuAn(tbl_SA_PhieuAn instance);
    partial void Deletetbl_SA_PhieuAn(tbl_SA_PhieuAn instance);
    #endregion
		
		public QLSuatAnDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLSuatAnDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLSuatAnDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLSuatAnDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_HT_MaVach> tbl_HT_MaVaches
		{
			get
			{
				return this.GetTable<tbl_HT_MaVach>();
			}
		}
		
		public System.Data.Linq.Table<tbl_SA_PhieuAn> tbl_SA_PhieuAns
		{
			get
			{
				return this.GetTable<tbl_SA_PhieuAn>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_SA_PhieuDangKySuatAn_Index")]
		public ISingleResult<sp_SA_PhieuDangKySuatAn_IndexResult> sp_SA_PhieuDangKySuatAn_Index([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string maNhanVien, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string maCuaHang, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string qSearch)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maNhanVien, maCuaHang, qSearch);
			return ((ISingleResult<sp_SA_PhieuDangKySuatAn_IndexResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_SA_DangKySuatAn_CongChuanNhanVien_TVWindow")]
		public ISingleResult<sp_SA_DangKySuatAn_CongChuanNhanVien_TVWindowResult> sp_SA_DangKySuatAn_CongChuanNhanVien_TVWindow([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> thang, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> nam)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), thang, nam);
			return ((ISingleResult<sp_SA_DangKySuatAn_CongChuanNhanVien_TVWindowResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_NS_DanhSachPhieuDangKySuatAn_Index")]
		public ISingleResult<sp_NS_DanhSachPhieuDangKySuatAn_IndexResult> sp_NS_DanhSachPhieuDangKySuatAn_Index([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(250)")] string maNhanVien, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(250)")] string maCuaHang, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> tuNgay, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> denNgay, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(250)")] string qSearch)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maNhanVien, maCuaHang, tuNgay, denNgay, qSearch);
			return ((ISingleResult<sp_NS_DanhSachPhieuDangKySuatAn_IndexResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_HT_MaVach")]
	public partial class tbl_HT_MaVach : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _maPhieu;
		
		private string _tenFileDinhKem;
		
		private string _tenFileDinhKemLuu;
		
		private string _enCoded;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnmaPhieuChanging(string value);
    partial void OnmaPhieuChanged();
    partial void OntenFileDinhKemChanging(string value);
    partial void OntenFileDinhKemChanged();
    partial void OntenFileDinhKemLuuChanging(string value);
    partial void OntenFileDinhKemLuuChanged();
    partial void OnenCodedChanging(string value);
    partial void OnenCodedChanged();
    #endregion
		
		public tbl_HT_MaVach()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maPhieu", DbType="VarChar(200)")]
		public string maPhieu
		{
			get
			{
				return this._maPhieu;
			}
			set
			{
				if ((this._maPhieu != value))
				{
					this.OnmaPhieuChanging(value);
					this.SendPropertyChanging();
					this._maPhieu = value;
					this.SendPropertyChanged("maPhieu");
					this.OnmaPhieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenFileDinhKem", DbType="NVarChar(MAX)")]
		public string tenFileDinhKem
		{
			get
			{
				return this._tenFileDinhKem;
			}
			set
			{
				if ((this._tenFileDinhKem != value))
				{
					this.OntenFileDinhKemChanging(value);
					this.SendPropertyChanging();
					this._tenFileDinhKem = value;
					this.SendPropertyChanged("tenFileDinhKem");
					this.OntenFileDinhKemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenFileDinhKemLuu", DbType="NVarChar(MAX)")]
		public string tenFileDinhKemLuu
		{
			get
			{
				return this._tenFileDinhKemLuu;
			}
			set
			{
				if ((this._tenFileDinhKemLuu != value))
				{
					this.OntenFileDinhKemLuuChanging(value);
					this.SendPropertyChanging();
					this._tenFileDinhKemLuu = value;
					this.SendPropertyChanged("tenFileDinhKemLuu");
					this.OntenFileDinhKemLuuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_enCoded", DbType="NVarChar(MAX)")]
		public string enCoded
		{
			get
			{
				return this._enCoded;
			}
			set
			{
				if ((this._enCoded != value))
				{
					this.OnenCodedChanging(value);
					this.SendPropertyChanging();
					this._enCoded = value;
					this.SendPropertyChanged("enCoded");
					this.OnenCodedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_SA_PhieuAn")]
	public partial class tbl_SA_PhieuAn : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _maPhieu;
		
		private string _nguoiLapPhieu;
		
		private string _maNhanVien;
		
		private System.Nullable<System.DateTime> _ngayLapPhieu;
		
		private string _maCuaHang;
		
		private string _maMonAn;
		
		private System.Nullable<int> _soThuTuPhucVuTaiQuan;
		
		private System.Nullable<int> _soSuatAnConLaiCuaNVTaiQuan;
		
		private string _maVach;
		
		private string _thoiGianDuKienPhucVu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnmaPhieuChanging(string value);
    partial void OnmaPhieuChanged();
    partial void OnnguoiLapPhieuChanging(string value);
    partial void OnnguoiLapPhieuChanged();
    partial void OnmaNhanVienChanging(string value);
    partial void OnmaNhanVienChanged();
    partial void OnngayLapPhieuChanging(System.Nullable<System.DateTime> value);
    partial void OnngayLapPhieuChanged();
    partial void OnmaCuaHangChanging(string value);
    partial void OnmaCuaHangChanged();
    partial void OnmaMonAnChanging(string value);
    partial void OnmaMonAnChanged();
    partial void OnsoThuTuPhucVuTaiQuanChanging(System.Nullable<int> value);
    partial void OnsoThuTuPhucVuTaiQuanChanged();
    partial void OnsoSuatAnConLaiCuaNVTaiQuanChanging(System.Nullable<int> value);
    partial void OnsoSuatAnConLaiCuaNVTaiQuanChanged();
    partial void OnmaVachChanging(string value);
    partial void OnmaVachChanged();
    partial void OnthoiGianDuKienPhucVuChanging(string value);
    partial void OnthoiGianDuKienPhucVuChanged();
    #endregion
		
		public tbl_SA_PhieuAn()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maPhieu", DbType="NVarChar(200) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maPhieu
		{
			get
			{
				return this._maPhieu;
			}
			set
			{
				if ((this._maPhieu != value))
				{
					this.OnmaPhieuChanging(value);
					this.SendPropertyChanging();
					this._maPhieu = value;
					this.SendPropertyChanged("maPhieu");
					this.OnmaPhieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nguoiLapPhieu", DbType="VarChar(30)")]
		public string nguoiLapPhieu
		{
			get
			{
				return this._nguoiLapPhieu;
			}
			set
			{
				if ((this._nguoiLapPhieu != value))
				{
					this.OnnguoiLapPhieuChanging(value);
					this.SendPropertyChanging();
					this._nguoiLapPhieu = value;
					this.SendPropertyChanged("nguoiLapPhieu");
					this.OnnguoiLapPhieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNhanVien", DbType="VarChar(50)")]
		public string maNhanVien
		{
			get
			{
				return this._maNhanVien;
			}
			set
			{
				if ((this._maNhanVien != value))
				{
					this.OnmaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._maNhanVien = value;
					this.SendPropertyChanged("maNhanVien");
					this.OnmaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayLapPhieu", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngayLapPhieu
		{
			get
			{
				return this._ngayLapPhieu;
			}
			set
			{
				if ((this._ngayLapPhieu != value))
				{
					this.OnngayLapPhieuChanging(value);
					this.SendPropertyChanging();
					this._ngayLapPhieu = value;
					this.SendPropertyChanged("ngayLapPhieu");
					this.OnngayLapPhieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maCuaHang", DbType="VarChar(50)")]
		public string maCuaHang
		{
			get
			{
				return this._maCuaHang;
			}
			set
			{
				if ((this._maCuaHang != value))
				{
					this.OnmaCuaHangChanging(value);
					this.SendPropertyChanging();
					this._maCuaHang = value;
					this.SendPropertyChanged("maCuaHang");
					this.OnmaCuaHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maMonAn", DbType="NVarChar(50)")]
		public string maMonAn
		{
			get
			{
				return this._maMonAn;
			}
			set
			{
				if ((this._maMonAn != value))
				{
					this.OnmaMonAnChanging(value);
					this.SendPropertyChanging();
					this._maMonAn = value;
					this.SendPropertyChanged("maMonAn");
					this.OnmaMonAnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soThuTuPhucVuTaiQuan", DbType="Int")]
		public System.Nullable<int> soThuTuPhucVuTaiQuan
		{
			get
			{
				return this._soThuTuPhucVuTaiQuan;
			}
			set
			{
				if ((this._soThuTuPhucVuTaiQuan != value))
				{
					this.OnsoThuTuPhucVuTaiQuanChanging(value);
					this.SendPropertyChanging();
					this._soThuTuPhucVuTaiQuan = value;
					this.SendPropertyChanged("soThuTuPhucVuTaiQuan");
					this.OnsoThuTuPhucVuTaiQuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soSuatAnConLaiCuaNVTaiQuan", DbType="Int")]
		public System.Nullable<int> soSuatAnConLaiCuaNVTaiQuan
		{
			get
			{
				return this._soSuatAnConLaiCuaNVTaiQuan;
			}
			set
			{
				if ((this._soSuatAnConLaiCuaNVTaiQuan != value))
				{
					this.OnsoSuatAnConLaiCuaNVTaiQuanChanging(value);
					this.SendPropertyChanging();
					this._soSuatAnConLaiCuaNVTaiQuan = value;
					this.SendPropertyChanged("soSuatAnConLaiCuaNVTaiQuan");
					this.OnsoSuatAnConLaiCuaNVTaiQuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maVach", DbType="NVarChar(500)")]
		public string maVach
		{
			get
			{
				return this._maVach;
			}
			set
			{
				if ((this._maVach != value))
				{
					this.OnmaVachChanging(value);
					this.SendPropertyChanging();
					this._maVach = value;
					this.SendPropertyChanged("maVach");
					this.OnmaVachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thoiGianDuKienPhucVu", DbType="NVarChar(500)")]
		public string thoiGianDuKienPhucVu
		{
			get
			{
				return this._thoiGianDuKienPhucVu;
			}
			set
			{
				if ((this._thoiGianDuKienPhucVu != value))
				{
					this.OnthoiGianDuKienPhucVuChanging(value);
					this.SendPropertyChanging();
					this._thoiGianDuKienPhucVu = value;
					this.SendPropertyChanged("thoiGianDuKienPhucVu");
					this.OnthoiGianDuKienPhucVuChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class sp_SA_PhieuDangKySuatAn_IndexResult
	{
		
		private int _id;
		
		private string _maPhieu;
		
		private string _nguoiLapPhieu;
		
		private string _maNhanVien;
		
		private System.Nullable<System.DateTime> _ngayLapPhieu;
		
		private string _maCuaHang;
		
		private System.Nullable<int> _soThuTuPhucVuTaiQuan;
		
		private System.Nullable<int> _soSuatAnConLaiCuaNVTaiQuan;
		
		private string _maVach;
		
		private string _hoVaTen;
		
		private string _tenCuaHang;
		
		private string _avatar;
		
		public sp_SA_PhieuDangKySuatAn_IndexResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maPhieu", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string maPhieu
		{
			get
			{
				return this._maPhieu;
			}
			set
			{
				if ((this._maPhieu != value))
				{
					this._maPhieu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nguoiLapPhieu", DbType="VarChar(30)")]
		public string nguoiLapPhieu
		{
			get
			{
				return this._nguoiLapPhieu;
			}
			set
			{
				if ((this._nguoiLapPhieu != value))
				{
					this._nguoiLapPhieu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNhanVien", DbType="VarChar(50)")]
		public string maNhanVien
		{
			get
			{
				return this._maNhanVien;
			}
			set
			{
				if ((this._maNhanVien != value))
				{
					this._maNhanVien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayLapPhieu", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngayLapPhieu
		{
			get
			{
				return this._ngayLapPhieu;
			}
			set
			{
				if ((this._ngayLapPhieu != value))
				{
					this._ngayLapPhieu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maCuaHang", DbType="VarChar(50)")]
		public string maCuaHang
		{
			get
			{
				return this._maCuaHang;
			}
			set
			{
				if ((this._maCuaHang != value))
				{
					this._maCuaHang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soThuTuPhucVuTaiQuan", DbType="Int")]
		public System.Nullable<int> soThuTuPhucVuTaiQuan
		{
			get
			{
				return this._soThuTuPhucVuTaiQuan;
			}
			set
			{
				if ((this._soThuTuPhucVuTaiQuan != value))
				{
					this._soThuTuPhucVuTaiQuan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soSuatAnConLaiCuaNVTaiQuan", DbType="Int")]
		public System.Nullable<int> soSuatAnConLaiCuaNVTaiQuan
		{
			get
			{
				return this._soSuatAnConLaiCuaNVTaiQuan;
			}
			set
			{
				if ((this._soSuatAnConLaiCuaNVTaiQuan != value))
				{
					this._soSuatAnConLaiCuaNVTaiQuan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maVach", DbType="NVarChar(500)")]
		public string maVach
		{
			get
			{
				return this._maVach;
			}
			set
			{
				if ((this._maVach != value))
				{
					this._maVach = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoVaTen", DbType="NVarChar(201)")]
		public string hoVaTen
		{
			get
			{
				return this._hoVaTen;
			}
			set
			{
				if ((this._hoVaTen != value))
				{
					this._hoVaTen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenCuaHang", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string tenCuaHang
		{
			get
			{
				return this._tenCuaHang;
			}
			set
			{
				if ((this._tenCuaHang != value))
				{
					this._tenCuaHang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_avatar", DbType="NVarChar(500)")]
		public string avatar
		{
			get
			{
				return this._avatar;
			}
			set
			{
				if ((this._avatar != value))
				{
					this._avatar = value;
				}
			}
		}
	}
	
	public partial class sp_SA_DangKySuatAn_CongChuanNhanVien_TVWindowResult
	{
		
		private string _maNhanVien;
		
		private string _tenNhanVien;
		
		private string _tenPhongBan;
		
		private System.Nullable<int> _congChuan;
		
		public sp_SA_DangKySuatAn_CongChuanNhanVien_TVWindowResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNhanVien", DbType="VarChar(30)")]
		public string maNhanVien
		{
			get
			{
				return this._maNhanVien;
			}
			set
			{
				if ((this._maNhanVien != value))
				{
					this._maNhanVien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenNhanVien", DbType="NVarChar(100)")]
		public string tenNhanVien
		{
			get
			{
				return this._tenNhanVien;
			}
			set
			{
				if ((this._tenNhanVien != value))
				{
					this._tenNhanVien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenPhongBan", DbType="NVarChar(200)")]
		public string tenPhongBan
		{
			get
			{
				return this._tenPhongBan;
			}
			set
			{
				if ((this._tenPhongBan != value))
				{
					this._tenPhongBan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_congChuan", DbType="Int")]
		public System.Nullable<int> congChuan
		{
			get
			{
				return this._congChuan;
			}
			set
			{
				if ((this._congChuan != value))
				{
					this._congChuan = value;
				}
			}
		}
	}
	
	public partial class sp_NS_DanhSachPhieuDangKySuatAn_IndexResult
	{
		
		private int _id;
		
		private string _maPhieu;
		
		private string _nguoiLapPhieu;
		
		private string _maNhanVien;
		
		private System.Nullable<System.DateTime> _ngayLapPhieu;
		
		private string _maCuaHang;
		
		private string _maMonAn;
		
		private System.Nullable<int> _soThuTuPhucVuTaiQuan;
		
		private System.Nullable<int> _soSuatAnConLaiCuaNVTaiQuan;
		
		private string _maVach;
		
		private string _thoiGianDuKienPhucVu;
		
		private string _tenCuaHang;
		
		private string _avatar;
		
		private string _hoVaTen;
		
		private string _hoTenNguoiLap;
		
		public sp_NS_DanhSachPhieuDangKySuatAn_IndexResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maPhieu", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string maPhieu
		{
			get
			{
				return this._maPhieu;
			}
			set
			{
				if ((this._maPhieu != value))
				{
					this._maPhieu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nguoiLapPhieu", DbType="VarChar(30)")]
		public string nguoiLapPhieu
		{
			get
			{
				return this._nguoiLapPhieu;
			}
			set
			{
				if ((this._nguoiLapPhieu != value))
				{
					this._nguoiLapPhieu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNhanVien", DbType="VarChar(50)")]
		public string maNhanVien
		{
			get
			{
				return this._maNhanVien;
			}
			set
			{
				if ((this._maNhanVien != value))
				{
					this._maNhanVien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayLapPhieu", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngayLapPhieu
		{
			get
			{
				return this._ngayLapPhieu;
			}
			set
			{
				if ((this._ngayLapPhieu != value))
				{
					this._ngayLapPhieu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maCuaHang", DbType="VarChar(50)")]
		public string maCuaHang
		{
			get
			{
				return this._maCuaHang;
			}
			set
			{
				if ((this._maCuaHang != value))
				{
					this._maCuaHang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maMonAn", DbType="NVarChar(50)")]
		public string maMonAn
		{
			get
			{
				return this._maMonAn;
			}
			set
			{
				if ((this._maMonAn != value))
				{
					this._maMonAn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soThuTuPhucVuTaiQuan", DbType="Int")]
		public System.Nullable<int> soThuTuPhucVuTaiQuan
		{
			get
			{
				return this._soThuTuPhucVuTaiQuan;
			}
			set
			{
				if ((this._soThuTuPhucVuTaiQuan != value))
				{
					this._soThuTuPhucVuTaiQuan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soSuatAnConLaiCuaNVTaiQuan", DbType="Int")]
		public System.Nullable<int> soSuatAnConLaiCuaNVTaiQuan
		{
			get
			{
				return this._soSuatAnConLaiCuaNVTaiQuan;
			}
			set
			{
				if ((this._soSuatAnConLaiCuaNVTaiQuan != value))
				{
					this._soSuatAnConLaiCuaNVTaiQuan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maVach", DbType="NVarChar(500)")]
		public string maVach
		{
			get
			{
				return this._maVach;
			}
			set
			{
				if ((this._maVach != value))
				{
					this._maVach = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thoiGianDuKienPhucVu", DbType="NVarChar(500)")]
		public string thoiGianDuKienPhucVu
		{
			get
			{
				return this._thoiGianDuKienPhucVu;
			}
			set
			{
				if ((this._thoiGianDuKienPhucVu != value))
				{
					this._thoiGianDuKienPhucVu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenCuaHang", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string tenCuaHang
		{
			get
			{
				return this._tenCuaHang;
			}
			set
			{
				if ((this._tenCuaHang != value))
				{
					this._tenCuaHang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_avatar", DbType="NVarChar(500)")]
		public string avatar
		{
			get
			{
				return this._avatar;
			}
			set
			{
				if ((this._avatar != value))
				{
					this._avatar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoVaTen", DbType="NVarChar(201)")]
		public string hoVaTen
		{
			get
			{
				return this._hoVaTen;
			}
			set
			{
				if ((this._hoVaTen != value))
				{
					this._hoVaTen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoTenNguoiLap", DbType="NVarChar(201)")]
		public string hoTenNguoiLap
		{
			get
			{
				return this._hoTenNguoiLap;
			}
			set
			{
				if ((this._hoTenNguoiLap != value))
				{
					this._hoTenNguoiLap = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
