#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatDongSan.Models.DBChamCong
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="adms_db")]
	public partial class DBChamCongDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertSys_Machine(Sys_Machine instance);
    partial void UpdateSys_Machine(Sys_Machine instance);
    partial void DeleteSys_Machine(Sys_Machine instance);
    partial void InsertSys_SiteConection(Sys_SiteConection instance);
    partial void UpdateSys_SiteConection(Sys_SiteConection instance);
    partial void DeleteSys_SiteConection(Sys_SiteConection instance);
    partial void Insertcheckinout(checkinout instance);
    partial void Updatecheckinout(checkinout instance);
    partial void Deletecheckinout(checkinout instance);
    #endregion
		
		public DBChamCongDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBChamCongDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBChamCongDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBChamCongDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Sys_Machine> Sys_Machines
		{
			get
			{
				return this.GetTable<Sys_Machine>();
			}
		}
		
		public System.Data.Linq.Table<Sys_SiteConection> Sys_SiteConections
		{
			get
			{
				return this.GetTable<Sys_SiteConection>();
			}
		}
		
		public System.Data.Linq.Table<checkinout> checkinouts
		{
			get
			{
				return this.GetTable<checkinout>();
			}
		}
		
		public System.Data.Linq.Table<userinfo> userinfos
		{
			get
			{
				return this.GetTable<userinfo>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Sp_ViewMachinePB")]
		public ISingleResult<Sp_ViewMachinePBResult> Sp_ViewMachinePB([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string maCongTrinh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string qSearch)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maCongTrinh, qSearch);
			return ((ISingleResult<Sp_ViewMachinePBResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_LayChamCongConThieuVeERP")]
		public ISingleResult<sp_LayChamCongConThieuVeERPResult> sp_LayChamCongConThieuVeERP([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string maCongTrinh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string maMayChamCong, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string qSearch, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> tuNgay, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> denNgay, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> thang, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> nam)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maCongTrinh, maMayChamCong, qSearch, tuNgay, denNgay, thang, nam);
			return ((ISingleResult<sp_LayChamCongConThieuVeERPResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sys_Machine")]
	public partial class Sys_Machine : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _siteId;
		
		private string _machineId;
		
		private string _MachineName;
		
		private string _remark;
		
		private System.Nullable<int> _typeMachine;
		
		private string _nguoiLap;
		
		private System.Nullable<System.DateTime> _ngayLap;
		
		private EntityRef<Sys_SiteConection> _Sys_SiteConection;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsiteIdChanging(string value);
    partial void OnsiteIdChanged();
    partial void OnmachineIdChanging(string value);
    partial void OnmachineIdChanged();
    partial void OnMachineNameChanging(string value);
    partial void OnMachineNameChanged();
    partial void OnremarkChanging(string value);
    partial void OnremarkChanged();
    partial void OntypeMachineChanging(System.Nullable<int> value);
    partial void OntypeMachineChanged();
    partial void OnnguoiLapChanging(string value);
    partial void OnnguoiLapChanged();
    partial void OnngayLapChanging(System.Nullable<System.DateTime> value);
    partial void OnngayLapChanged();
    #endregion
		
		public Sys_Machine()
		{
			this._Sys_SiteConection = default(EntityRef<Sys_SiteConection>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siteId", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string siteId
		{
			get
			{
				return this._siteId;
			}
			set
			{
				if ((this._siteId != value))
				{
					if (this._Sys_SiteConection.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnsiteIdChanging(value);
					this.SendPropertyChanging();
					this._siteId = value;
					this.SendPropertyChanged("siteId");
					this.OnsiteIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_machineId", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string machineId
		{
			get
			{
				return this._machineId;
			}
			set
			{
				if ((this._machineId != value))
				{
					this.OnmachineIdChanging(value);
					this.SendPropertyChanging();
					this._machineId = value;
					this.SendPropertyChanged("machineId");
					this.OnmachineIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MachineName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MachineName
		{
			get
			{
				return this._MachineName;
			}
			set
			{
				if ((this._MachineName != value))
				{
					this.OnMachineNameChanging(value);
					this.SendPropertyChanging();
					this._MachineName = value;
					this.SendPropertyChanged("MachineName");
					this.OnMachineNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_remark", DbType="NVarChar(150)")]
		public string remark
		{
			get
			{
				return this._remark;
			}
			set
			{
				if ((this._remark != value))
				{
					this.OnremarkChanging(value);
					this.SendPropertyChanging();
					this._remark = value;
					this.SendPropertyChanged("remark");
					this.OnremarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_typeMachine", DbType="Int")]
		public System.Nullable<int> typeMachine
		{
			get
			{
				return this._typeMachine;
			}
			set
			{
				if ((this._typeMachine != value))
				{
					this.OntypeMachineChanging(value);
					this.SendPropertyChanging();
					this._typeMachine = value;
					this.SendPropertyChanged("typeMachine");
					this.OntypeMachineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nguoiLap", DbType="NVarChar(100)")]
		public string nguoiLap
		{
			get
			{
				return this._nguoiLap;
			}
			set
			{
				if ((this._nguoiLap != value))
				{
					this.OnnguoiLapChanging(value);
					this.SendPropertyChanging();
					this._nguoiLap = value;
					this.SendPropertyChanged("nguoiLap");
					this.OnnguoiLapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayLap", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngayLap
		{
			get
			{
				return this._ngayLap;
			}
			set
			{
				if ((this._ngayLap != value))
				{
					this.OnngayLapChanging(value);
					this.SendPropertyChanging();
					this._ngayLap = value;
					this.SendPropertyChanged("ngayLap");
					this.OnngayLapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Sys_SiteConection_Sys_Machine", Storage="_Sys_SiteConection", ThisKey="siteId", OtherKey="siteId", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Sys_SiteConection Sys_SiteConection
		{
			get
			{
				return this._Sys_SiteConection.Entity;
			}
			set
			{
				Sys_SiteConection previousValue = this._Sys_SiteConection.Entity;
				if (((previousValue != value) 
							|| (this._Sys_SiteConection.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Sys_SiteConection.Entity = null;
						previousValue.Sys_Machines.Remove(this);
					}
					this._Sys_SiteConection.Entity = value;
					if ((value != null))
					{
						value.Sys_Machines.Add(this);
						this._siteId = value.siteId;
					}
					else
					{
						this._siteId = default(string);
					}
					this.SendPropertyChanged("Sys_SiteConection");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sys_SiteConection")]
	public partial class Sys_SiteConection : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _siteId;
		
		private string _siteName;
		
		private string _siteAddress;
		
		private string _siteIP;
		
		private string _port;
		
		private string _loginName;
		
		private string _pdw;
		
		private string _databaseName;
		
		private string _remark;
		
		private string _nguoiLap;
		
		private System.Nullable<System.DateTime> _ngayLap;
		
		private EntitySet<Sys_Machine> _Sys_Machines;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsiteIdChanging(string value);
    partial void OnsiteIdChanged();
    partial void OnsiteNameChanging(string value);
    partial void OnsiteNameChanged();
    partial void OnsiteAddressChanging(string value);
    partial void OnsiteAddressChanged();
    partial void OnsiteIPChanging(string value);
    partial void OnsiteIPChanged();
    partial void OnportChanging(string value);
    partial void OnportChanged();
    partial void OnloginNameChanging(string value);
    partial void OnloginNameChanged();
    partial void OnpdwChanging(string value);
    partial void OnpdwChanged();
    partial void OndatabaseNameChanging(string value);
    partial void OndatabaseNameChanged();
    partial void OnremarkChanging(string value);
    partial void OnremarkChanged();
    partial void OnnguoiLapChanging(string value);
    partial void OnnguoiLapChanged();
    partial void OnngayLapChanging(System.Nullable<System.DateTime> value);
    partial void OnngayLapChanged();
    #endregion
		
		public Sys_SiteConection()
		{
			this._Sys_Machines = new EntitySet<Sys_Machine>(new Action<Sys_Machine>(this.attach_Sys_Machines), new Action<Sys_Machine>(this.detach_Sys_Machines));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siteId", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string siteId
		{
			get
			{
				return this._siteId;
			}
			set
			{
				if ((this._siteId != value))
				{
					this.OnsiteIdChanging(value);
					this.SendPropertyChanging();
					this._siteId = value;
					this.SendPropertyChanged("siteId");
					this.OnsiteIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siteName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string siteName
		{
			get
			{
				return this._siteName;
			}
			set
			{
				if ((this._siteName != value))
				{
					this.OnsiteNameChanging(value);
					this.SendPropertyChanging();
					this._siteName = value;
					this.SendPropertyChanged("siteName");
					this.OnsiteNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siteAddress", DbType="NVarChar(150)")]
		public string siteAddress
		{
			get
			{
				return this._siteAddress;
			}
			set
			{
				if ((this._siteAddress != value))
				{
					this.OnsiteAddressChanging(value);
					this.SendPropertyChanging();
					this._siteAddress = value;
					this.SendPropertyChanged("siteAddress");
					this.OnsiteAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siteIP", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string siteIP
		{
			get
			{
				return this._siteIP;
			}
			set
			{
				if ((this._siteIP != value))
				{
					this.OnsiteIPChanging(value);
					this.SendPropertyChanging();
					this._siteIP = value;
					this.SendPropertyChanged("siteIP");
					this.OnsiteIPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_port", DbType="VarChar(7)")]
		public string port
		{
			get
			{
				return this._port;
			}
			set
			{
				if ((this._port != value))
				{
					this.OnportChanging(value);
					this.SendPropertyChanging();
					this._port = value;
					this.SendPropertyChanged("port");
					this.OnportChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loginName", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string loginName
		{
			get
			{
				return this._loginName;
			}
			set
			{
				if ((this._loginName != value))
				{
					this.OnloginNameChanging(value);
					this.SendPropertyChanging();
					this._loginName = value;
					this.SendPropertyChanged("loginName");
					this.OnloginNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pdw", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string pdw
		{
			get
			{
				return this._pdw;
			}
			set
			{
				if ((this._pdw != value))
				{
					this.OnpdwChanging(value);
					this.SendPropertyChanging();
					this._pdw = value;
					this.SendPropertyChanged("pdw");
					this.OnpdwChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_databaseName", DbType="VarChar(30)")]
		public string databaseName
		{
			get
			{
				return this._databaseName;
			}
			set
			{
				if ((this._databaseName != value))
				{
					this.OndatabaseNameChanging(value);
					this.SendPropertyChanging();
					this._databaseName = value;
					this.SendPropertyChanged("databaseName");
					this.OndatabaseNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_remark", DbType="NVarChar(250)")]
		public string remark
		{
			get
			{
				return this._remark;
			}
			set
			{
				if ((this._remark != value))
				{
					this.OnremarkChanging(value);
					this.SendPropertyChanging();
					this._remark = value;
					this.SendPropertyChanged("remark");
					this.OnremarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nguoiLap", DbType="NVarChar(100)")]
		public string nguoiLap
		{
			get
			{
				return this._nguoiLap;
			}
			set
			{
				if ((this._nguoiLap != value))
				{
					this.OnnguoiLapChanging(value);
					this.SendPropertyChanging();
					this._nguoiLap = value;
					this.SendPropertyChanged("nguoiLap");
					this.OnnguoiLapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayLap", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngayLap
		{
			get
			{
				return this._ngayLap;
			}
			set
			{
				if ((this._ngayLap != value))
				{
					this.OnngayLapChanging(value);
					this.SendPropertyChanging();
					this._ngayLap = value;
					this.SendPropertyChanged("ngayLap");
					this.OnngayLapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Sys_SiteConection_Sys_Machine", Storage="_Sys_Machines", ThisKey="siteId", OtherKey="siteId")]
		public EntitySet<Sys_Machine> Sys_Machines
		{
			get
			{
				return this._Sys_Machines;
			}
			set
			{
				this._Sys_Machines.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Sys_Machines(Sys_Machine entity)
		{
			this.SendPropertyChanging();
			entity.Sys_SiteConection = this;
		}
		
		private void detach_Sys_Machines(Sys_Machine entity)
		{
			this.SendPropertyChanging();
			entity.Sys_SiteConection = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.checkinout")]
	public partial class checkinout : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _userid;
		
		private System.Nullable<System.DateTime> _checktime;
		
		private string _checktype;
		
		private System.Nullable<int> _verifycode;
		
		private string _SN;
		
		private string _sensorid;
		
		private string _WorkCode;
		
		private string _Reserved;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnuseridChanging(System.Nullable<int> value);
    partial void OnuseridChanged();
    partial void OnchecktimeChanging(System.Nullable<System.DateTime> value);
    partial void OnchecktimeChanged();
    partial void OnchecktypeChanging(string value);
    partial void OnchecktypeChanged();
    partial void OnverifycodeChanging(System.Nullable<int> value);
    partial void OnverifycodeChanged();
    partial void OnSNChanging(string value);
    partial void OnSNChanged();
    partial void OnsensoridChanging(string value);
    partial void OnsensoridChanged();
    partial void OnWorkCodeChanging(string value);
    partial void OnWorkCodeChanged();
    partial void OnReservedChanging(string value);
    partial void OnReservedChanged();
    #endregion
		
		public checkinout()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="Int")]
		public System.Nullable<int> userid
		{
			get
			{
				return this._userid;
			}
			set
			{
				if ((this._userid != value))
				{
					this.OnuseridChanging(value);
					this.SendPropertyChanging();
					this._userid = value;
					this.SendPropertyChanged("userid");
					this.OnuseridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_checktime", DbType="DateTime")]
		public System.Nullable<System.DateTime> checktime
		{
			get
			{
				return this._checktime;
			}
			set
			{
				if ((this._checktime != value))
				{
					this.OnchecktimeChanging(value);
					this.SendPropertyChanging();
					this._checktime = value;
					this.SendPropertyChanged("checktime");
					this.OnchecktimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_checktype", DbType="VarChar(1)")]
		public string checktype
		{
			get
			{
				return this._checktype;
			}
			set
			{
				if ((this._checktype != value))
				{
					this.OnchecktypeChanging(value);
					this.SendPropertyChanging();
					this._checktype = value;
					this.SendPropertyChanged("checktype");
					this.OnchecktypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_verifycode", DbType="Int")]
		public System.Nullable<int> verifycode
		{
			get
			{
				return this._verifycode;
			}
			set
			{
				if ((this._verifycode != value))
				{
					this.OnverifycodeChanging(value);
					this.SendPropertyChanging();
					this._verifycode = value;
					this.SendPropertyChanged("verifycode");
					this.OnverifycodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SN", DbType="VarChar(20)")]
		public string SN
		{
			get
			{
				return this._SN;
			}
			set
			{
				if ((this._SN != value))
				{
					this.OnSNChanging(value);
					this.SendPropertyChanging();
					this._SN = value;
					this.SendPropertyChanged("SN");
					this.OnSNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sensorid", DbType="VarChar(5)")]
		public string sensorid
		{
			get
			{
				return this._sensorid;
			}
			set
			{
				if ((this._sensorid != value))
				{
					this.OnsensoridChanging(value);
					this.SendPropertyChanging();
					this._sensorid = value;
					this.SendPropertyChanged("sensorid");
					this.OnsensoridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WorkCode", DbType="VarChar(20)")]
		public string WorkCode
		{
			get
			{
				return this._WorkCode;
			}
			set
			{
				if ((this._WorkCode != value))
				{
					this.OnWorkCodeChanging(value);
					this.SendPropertyChanging();
					this._WorkCode = value;
					this.SendPropertyChanged("WorkCode");
					this.OnWorkCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reserved", DbType="VarChar(20)")]
		public string Reserved
		{
			get
			{
				return this._Reserved;
			}
			set
			{
				if ((this._Reserved != value))
				{
					this.OnReservedChanging(value);
					this.SendPropertyChanging();
					this._Reserved = value;
					this.SendPropertyChanged("Reserved");
					this.OnReservedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.userinfo")]
	public partial class userinfo
	{
		
		private int _userid;
		
		private string _badgenumber;
		
		private System.Nullable<int> _defaultdeptid;
		
		private string _name;
		
		private string _Password;
		
		private string _Card;
		
		private System.Nullable<int> _Privilege;
		
		private System.Nullable<int> _AccGroup;
		
		private string _TimeZones;
		
		private string _Gender;
		
		private System.Nullable<System.DateTime> _Birthday;
		
		private string _street;
		
		private string _zip;
		
		private string _ophone;
		
		private string _FPHONE;
		
		private string _pager;
		
		private string _minzu;
		
		private string _title;
		
		private string _SN;
		
		private string _SSN;
		
		private System.Nullable<System.DateTime> _UTime;
		
		private string _State;
		
		private string _City;
		
		private System.Nullable<short> _SECURITYFLAGS;
		
		private System.Nullable<short> _DelTag;
		
		private System.Nullable<int> _RegisterOT;
		
		private System.Nullable<int> _AutoSchPlan;
		
		private System.Nullable<int> _MinAutoSchInterval;
		
		private System.Nullable<int> _Image_id;
		
		public userinfo()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int userid
		{
			get
			{
				return this._userid;
			}
			set
			{
				if ((this._userid != value))
				{
					this._userid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_badgenumber", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string badgenumber
		{
			get
			{
				return this._badgenumber;
			}
			set
			{
				if ((this._badgenumber != value))
				{
					this._badgenumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_defaultdeptid", DbType="Int")]
		public System.Nullable<int> defaultdeptid
		{
			get
			{
				return this._defaultdeptid;
			}
			set
			{
				if ((this._defaultdeptid != value))
				{
					this._defaultdeptid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(40)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(20)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Card", DbType="VarChar(20)")]
		public string Card
		{
			get
			{
				return this._Card;
			}
			set
			{
				if ((this._Card != value))
				{
					this._Card = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Privilege", DbType="Int")]
		public System.Nullable<int> Privilege
		{
			get
			{
				return this._Privilege;
			}
			set
			{
				if ((this._Privilege != value))
				{
					this._Privilege = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccGroup", DbType="Int")]
		public System.Nullable<int> AccGroup
		{
			get
			{
				return this._AccGroup;
			}
			set
			{
				if ((this._AccGroup != value))
				{
					this._AccGroup = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeZones", DbType="VarChar(20)")]
		public string TimeZones
		{
			get
			{
				return this._TimeZones;
			}
			set
			{
				if ((this._TimeZones != value))
				{
					this._TimeZones = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="VarChar(2)")]
		public string Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this._Gender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Birthday", DbType="DateTime2")]
		public System.Nullable<System.DateTime> Birthday
		{
			get
			{
				return this._Birthday;
			}
			set
			{
				if ((this._Birthday != value))
				{
					this._Birthday = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_street", DbType="VarChar(40)")]
		public string street
		{
			get
			{
				return this._street;
			}
			set
			{
				if ((this._street != value))
				{
					this._street = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zip", DbType="VarChar(6)")]
		public string zip
		{
			get
			{
				return this._zip;
			}
			set
			{
				if ((this._zip != value))
				{
					this._zip = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ophone", DbType="VarChar(20)")]
		public string ophone
		{
			get
			{
				return this._ophone;
			}
			set
			{
				if ((this._ophone != value))
				{
					this._ophone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FPHONE", DbType="VarChar(20)")]
		public string FPHONE
		{
			get
			{
				return this._FPHONE;
			}
			set
			{
				if ((this._FPHONE != value))
				{
					this._FPHONE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pager", DbType="VarChar(20)")]
		public string pager
		{
			get
			{
				return this._pager;
			}
			set
			{
				if ((this._pager != value))
				{
					this._pager = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_minzu", DbType="VarChar(8)")]
		public string minzu
		{
			get
			{
				return this._minzu;
			}
			set
			{
				if ((this._minzu != value))
				{
					this._minzu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="VarChar(20)")]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this._title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SN", DbType="VarChar(20)")]
		public string SN
		{
			get
			{
				return this._SN;
			}
			set
			{
				if ((this._SN != value))
				{
					this._SN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SSN", DbType="VarChar(20)")]
		public string SSN
		{
			get
			{
				return this._SSN;
			}
			set
			{
				if ((this._SSN != value))
				{
					this._SSN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> UTime
		{
			get
			{
				return this._UTime;
			}
			set
			{
				if ((this._UTime != value))
				{
					this._UTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="VarChar(2)")]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this._State = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="VarChar(2)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this._City = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SECURITYFLAGS", DbType="SmallInt")]
		public System.Nullable<short> SECURITYFLAGS
		{
			get
			{
				return this._SECURITYFLAGS;
			}
			set
			{
				if ((this._SECURITYFLAGS != value))
				{
					this._SECURITYFLAGS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DelTag", DbType="SmallInt")]
		public System.Nullable<short> DelTag
		{
			get
			{
				return this._DelTag;
			}
			set
			{
				if ((this._DelTag != value))
				{
					this._DelTag = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegisterOT", DbType="Int")]
		public System.Nullable<int> RegisterOT
		{
			get
			{
				return this._RegisterOT;
			}
			set
			{
				if ((this._RegisterOT != value))
				{
					this._RegisterOT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AutoSchPlan", DbType="Int")]
		public System.Nullable<int> AutoSchPlan
		{
			get
			{
				return this._AutoSchPlan;
			}
			set
			{
				if ((this._AutoSchPlan != value))
				{
					this._AutoSchPlan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinAutoSchInterval", DbType="Int")]
		public System.Nullable<int> MinAutoSchInterval
		{
			get
			{
				return this._MinAutoSchInterval;
			}
			set
			{
				if ((this._MinAutoSchInterval != value))
				{
					this._MinAutoSchInterval = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Image_id", DbType="Int")]
		public System.Nullable<int> Image_id
		{
			get
			{
				return this._Image_id;
			}
			set
			{
				if ((this._Image_id != value))
				{
					this._Image_id = value;
				}
			}
		}
	}
	
	public partial class Sp_ViewMachinePBResult
	{
		
		private string _siteId;
		
		private string _machineId;
		
		private string _MachineName;
		
		private string _remark;
		
		private System.Nullable<int> _typeMachine;
		
		private string _siteName;
		
		private int _trangThai;
		
		private System.Nullable<System.DateTime> _LastActivity;
		
		private string _IPAddress;
		
		private System.Nullable<int> _FPCount;
		
		private System.Nullable<int> _TransactionCount;
		
		private System.Nullable<int> _UserCount;
		
		public Sp_ViewMachinePBResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siteId", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string siteId
		{
			get
			{
				return this._siteId;
			}
			set
			{
				if ((this._siteId != value))
				{
					this._siteId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_machineId", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string machineId
		{
			get
			{
				return this._machineId;
			}
			set
			{
				if ((this._machineId != value))
				{
					this._machineId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MachineName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MachineName
		{
			get
			{
				return this._MachineName;
			}
			set
			{
				if ((this._MachineName != value))
				{
					this._MachineName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_remark", DbType="NVarChar(150)")]
		public string remark
		{
			get
			{
				return this._remark;
			}
			set
			{
				if ((this._remark != value))
				{
					this._remark = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_typeMachine", DbType="Int")]
		public System.Nullable<int> typeMachine
		{
			get
			{
				return this._typeMachine;
			}
			set
			{
				if ((this._typeMachine != value))
				{
					this._typeMachine = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siteName", DbType="NVarChar(100)")]
		public string siteName
		{
			get
			{
				return this._siteName;
			}
			set
			{
				if ((this._siteName != value))
				{
					this._siteName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangThai", DbType="Int NOT NULL")]
		public int trangThai
		{
			get
			{
				return this._trangThai;
			}
			set
			{
				if ((this._trangThai != value))
				{
					this._trangThai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastActivity", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastActivity
		{
			get
			{
				return this._LastActivity;
			}
			set
			{
				if ((this._LastActivity != value))
				{
					this._LastActivity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IPAddress", DbType="VarChar(20)")]
		public string IPAddress
		{
			get
			{
				return this._IPAddress;
			}
			set
			{
				if ((this._IPAddress != value))
				{
					this._IPAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FPCount", DbType="Int")]
		public System.Nullable<int> FPCount
		{
			get
			{
				return this._FPCount;
			}
			set
			{
				if ((this._FPCount != value))
				{
					this._FPCount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransactionCount", DbType="Int")]
		public System.Nullable<int> TransactionCount
		{
			get
			{
				return this._TransactionCount;
			}
			set
			{
				if ((this._TransactionCount != value))
				{
					this._TransactionCount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserCount", DbType="Int")]
		public System.Nullable<int> UserCount
		{
			get
			{
				return this._UserCount;
			}
			set
			{
				if ((this._UserCount != value))
				{
					this._UserCount = value;
				}
			}
		}
	}
	
	public partial class sp_LayChamCongConThieuVeERPResult
	{
		
		private System.Nullable<int> _userid;
		
		private string _badgenumber;
		
		private string _SN;
		
		private System.Nullable<int> _idQuet;
		
		private System.Nullable<System.DateTime> _checktime;
		
		public sp_LayChamCongConThieuVeERPResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="Int")]
		public System.Nullable<int> userid
		{
			get
			{
				return this._userid;
			}
			set
			{
				if ((this._userid != value))
				{
					this._userid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_badgenumber", DbType="VarChar(20)")]
		public string badgenumber
		{
			get
			{
				return this._badgenumber;
			}
			set
			{
				if ((this._badgenumber != value))
				{
					this._badgenumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SN", DbType="VarChar(20)")]
		public string SN
		{
			get
			{
				return this._SN;
			}
			set
			{
				if ((this._SN != value))
				{
					this._SN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idQuet", DbType="Int")]
		public System.Nullable<int> idQuet
		{
			get
			{
				return this._idQuet;
			}
			set
			{
				if ((this._idQuet != value))
				{
					this._idQuet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_checktime", DbType="DateTime")]
		public System.Nullable<System.DateTime> checktime
		{
			get
			{
				return this._checktime;
			}
			set
			{
				if ((this._checktime != value))
				{
					this._checktime = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
