#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatDongSan.Models.QLSuatAn.LuuVet
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLySuatAnNhanSuChung")]
	public partial class QLSALuuVetDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_SA_CuaHang_TinhTrangGuiMail(tbl_SA_CuaHang_TinhTrangGuiMail instance);
    partial void Updatetbl_SA_CuaHang_TinhTrangGuiMail(tbl_SA_CuaHang_TinhTrangGuiMail instance);
    partial void Deletetbl_SA_CuaHang_TinhTrangGuiMail(tbl_SA_CuaHang_TinhTrangGuiMail instance);
    partial void Inserttbl_SA_CuaHang_MonAn(tbl_SA_CuaHang_MonAn instance);
    partial void Updatetbl_SA_CuaHang_MonAn(tbl_SA_CuaHang_MonAn instance);
    partial void Deletetbl_SA_CuaHang_MonAn(tbl_SA_CuaHang_MonAn instance);
    partial void Inserttbl_SA_NhanVienDangKySuatAnTrongThang(tbl_SA_NhanVienDangKySuatAnTrongThang instance);
    partial void Updatetbl_SA_NhanVienDangKySuatAnTrongThang(tbl_SA_NhanVienDangKySuatAnTrongThang instance);
    partial void Deletetbl_SA_NhanVienDangKySuatAnTrongThang(tbl_SA_NhanVienDangKySuatAnTrongThang instance);
    partial void Inserttbl_SA_CuaHang(tbl_SA_CuaHang instance);
    partial void Updatetbl_SA_CuaHang(tbl_SA_CuaHang instance);
    partial void Deletetbl_SA_CuaHang(tbl_SA_CuaHang instance);
    partial void Inserttbl_SA_DuyetPhanBo(tbl_SA_DuyetPhanBo instance);
    partial void Updatetbl_SA_DuyetPhanBo(tbl_SA_DuyetPhanBo instance);
    partial void Deletetbl_SA_DuyetPhanBo(tbl_SA_DuyetPhanBo instance);
    partial void Inserttbl_SA_PhieuDangKySuatAn_LuuVet(tbl_SA_PhieuDangKySuatAn_LuuVet instance);
    partial void Updatetbl_SA_PhieuDangKySuatAn_LuuVet(tbl_SA_PhieuDangKySuatAn_LuuVet instance);
    partial void Deletetbl_SA_PhieuDangKySuatAn_LuuVet(tbl_SA_PhieuDangKySuatAn_LuuVet instance);
    #endregion
		
		public QLSALuuVetDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLSALuuVetDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLSALuuVetDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLSALuuVetDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_SA_CuaHang_TinhTrangGuiMail> tbl_SA_CuaHang_TinhTrangGuiMails
		{
			get
			{
				return this.GetTable<tbl_SA_CuaHang_TinhTrangGuiMail>();
			}
		}
		
		public System.Data.Linq.Table<tbl_SA_CuaHang_MonAn> tbl_SA_CuaHang_MonAns
		{
			get
			{
				return this.GetTable<tbl_SA_CuaHang_MonAn>();
			}
		}
		
		public System.Data.Linq.Table<tbl_SA_NhanVienDangKySuatAnTrongThang> tbl_SA_NhanVienDangKySuatAnTrongThangs
		{
			get
			{
				return this.GetTable<tbl_SA_NhanVienDangKySuatAnTrongThang>();
			}
		}
		
		public System.Data.Linq.Table<tbl_SA_CuaHang> tbl_SA_CuaHangs
		{
			get
			{
				return this.GetTable<tbl_SA_CuaHang>();
			}
		}
		
		public System.Data.Linq.Table<tbl_SA_DuyetPhanBo> tbl_SA_DuyetPhanBos
		{
			get
			{
				return this.GetTable<tbl_SA_DuyetPhanBo>();
			}
		}
		
		public System.Data.Linq.Table<tbl_SA_PhieuDangKySuatAn_LuuVet> tbl_SA_PhieuDangKySuatAn_LuuVets
		{
			get
			{
				return this.GetTable<tbl_SA_PhieuDangKySuatAn_LuuVet>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_SA_NhanVienDangKySuatAnTrongThang_PhanBo")]
		public int sp_SA_NhanVienDangKySuatAnTrongThang_PhanBo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> thang, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> nam)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), thang, nam);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_SA_PhanBoCuaHangCongChuan_Index")]
		public ISingleResult<sp_SA_PhanBoCuaHangCongChuan_IndexResult> sp_SA_PhanBoCuaHangCongChuan_Index([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> thang, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> nam)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), thang, nam);
			return ((ISingleResult<sp_SA_PhanBoCuaHangCongChuan_IndexResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_CuaHang_MonAn_NhanVien_Index")]
		public ISingleResult<sp_CuaHang_MonAn_NhanVien_IndexResult> sp_CuaHang_MonAn_NhanVien_Index([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string qsearch, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string maCuaHang, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string maCongTy)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), qsearch, maCuaHang, maCongTy);
			return ((ISingleResult<sp_CuaHang_MonAn_NhanVien_IndexResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_SA_NhanVienDangKySuatAnTrongThang_Index")]
		public ISingleResult<sp_SA_NhanVienDangKySuatAnTrongThang_IndexResult> sp_SA_NhanVienDangKySuatAnTrongThang_Index([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> thang, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> nam, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> congChuan)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), thang, nam, congChuan);
			return ((ISingleResult<sp_SA_NhanVienDangKySuatAnTrongThang_IndexResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_SA_BC_ThongKeSuatAnTheoTungCuaHang")]
		public ISingleResult<sp_SA_BC_ThongKeSuatAnTheoTungCuaHangResult> sp_SA_BC_ThongKeSuatAnTheoTungCuaHang([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> thang, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> nam)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), thang, nam);
			return ((ISingleResult<sp_SA_BC_ThongKeSuatAnTheoTungCuaHangResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_SA_BC_ThongKeSuatAnTungNhanVien")]
		public ISingleResult<sp_SA_BC_ThongKeSuatAnTungNhanVienResult> sp_SA_BC_ThongKeSuatAnTungNhanVien([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string maCongTy, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string maCuaHang, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> tuNgay, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> denNgay, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string qsearch, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> page, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> rowInPage)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maCongTy, maCuaHang, tuNgay, denNgay, qsearch, page, rowInPage);
			return ((ISingleResult<sp_SA_BC_ThongKeSuatAnTungNhanVienResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_SA_PhieuDangKySuatAn_CuaHang_LuuVet_PhanBo")]
		public ISingleResult<sp_SA_PhieuDangKySuatAn_CuaHang_LuuVet_PhanBoResult> sp_SA_PhieuDangKySuatAn_CuaHang_LuuVet_PhanBo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string maNhanVien, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string maCongTy)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maNhanVien, maCongTy);
			return ((ISingleResult<sp_SA_PhieuDangKySuatAn_CuaHang_LuuVet_PhanBoResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_SA_CuaHang_TinhTrangGuiMail")]
	public partial class tbl_SA_CuaHang_TinhTrangGuiMail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _maCuaHang;
		
		private string _tenCuaHang;
		
		private string _ghiChu;
		
		private System.Nullable<System.DateTime> _ngayLap;
		
		private string _nguoiLap;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnmaCuaHangChanging(string value);
    partial void OnmaCuaHangChanged();
    partial void OntenCuaHangChanging(string value);
    partial void OntenCuaHangChanged();
    partial void OnghiChuChanging(string value);
    partial void OnghiChuChanged();
    partial void OnngayLapChanging(System.Nullable<System.DateTime> value);
    partial void OnngayLapChanged();
    partial void OnnguoiLapChanging(string value);
    partial void OnnguoiLapChanged();
    #endregion
		
		public tbl_SA_CuaHang_TinhTrangGuiMail()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maCuaHang", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string maCuaHang
		{
			get
			{
				return this._maCuaHang;
			}
			set
			{
				if ((this._maCuaHang != value))
				{
					this.OnmaCuaHangChanging(value);
					this.SendPropertyChanging();
					this._maCuaHang = value;
					this.SendPropertyChanged("maCuaHang");
					this.OnmaCuaHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenCuaHang", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string tenCuaHang
		{
			get
			{
				return this._tenCuaHang;
			}
			set
			{
				if ((this._tenCuaHang != value))
				{
					this.OntenCuaHangChanging(value);
					this.SendPropertyChanging();
					this._tenCuaHang = value;
					this.SendPropertyChanged("tenCuaHang");
					this.OntenCuaHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghiChu", DbType="NVarChar(500)")]
		public string ghiChu
		{
			get
			{
				return this._ghiChu;
			}
			set
			{
				if ((this._ghiChu != value))
				{
					this.OnghiChuChanging(value);
					this.SendPropertyChanging();
					this._ghiChu = value;
					this.SendPropertyChanged("ghiChu");
					this.OnghiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayLap", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngayLap
		{
			get
			{
				return this._ngayLap;
			}
			set
			{
				if ((this._ngayLap != value))
				{
					this.OnngayLapChanging(value);
					this.SendPropertyChanging();
					this._ngayLap = value;
					this.SendPropertyChanged("ngayLap");
					this.OnngayLapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nguoiLap", DbType="VarChar(30)")]
		public string nguoiLap
		{
			get
			{
				return this._nguoiLap;
			}
			set
			{
				if ((this._nguoiLap != value))
				{
					this.OnnguoiLapChanging(value);
					this.SendPropertyChanging();
					this._nguoiLap = value;
					this.SendPropertyChanged("nguoiLap");
					this.OnnguoiLapChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_SA_CuaHang_MonAn")]
	public partial class tbl_SA_CuaHang_MonAn : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _maMonAn;
		
		private string _maCuaHang;
		
		private string _tenMonAn;
		
		private string _ghiChu;
		
		private System.Nullable<int> _soLuongMonAn;
		
		private System.Nullable<System.DateTime> _ngayLap;
		
		private string _nguoiLap;
		
		private string _avatar;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnmaMonAnChanging(string value);
    partial void OnmaMonAnChanged();
    partial void OnmaCuaHangChanging(string value);
    partial void OnmaCuaHangChanged();
    partial void OntenMonAnChanging(string value);
    partial void OntenMonAnChanged();
    partial void OnghiChuChanging(string value);
    partial void OnghiChuChanged();
    partial void OnsoLuongMonAnChanging(System.Nullable<int> value);
    partial void OnsoLuongMonAnChanged();
    partial void OnngayLapChanging(System.Nullable<System.DateTime> value);
    partial void OnngayLapChanged();
    partial void OnnguoiLapChanging(string value);
    partial void OnnguoiLapChanged();
    partial void OnavatarChanging(string value);
    partial void OnavatarChanged();
    #endregion
		
		public tbl_SA_CuaHang_MonAn()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maMonAn", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maMonAn
		{
			get
			{
				return this._maMonAn;
			}
			set
			{
				if ((this._maMonAn != value))
				{
					this.OnmaMonAnChanging(value);
					this.SendPropertyChanging();
					this._maMonAn = value;
					this.SendPropertyChanged("maMonAn");
					this.OnmaMonAnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maCuaHang", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string maCuaHang
		{
			get
			{
				return this._maCuaHang;
			}
			set
			{
				if ((this._maCuaHang != value))
				{
					this.OnmaCuaHangChanging(value);
					this.SendPropertyChanging();
					this._maCuaHang = value;
					this.SendPropertyChanged("maCuaHang");
					this.OnmaCuaHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenMonAn", DbType="NVarChar(500)")]
		public string tenMonAn
		{
			get
			{
				return this._tenMonAn;
			}
			set
			{
				if ((this._tenMonAn != value))
				{
					this.OntenMonAnChanging(value);
					this.SendPropertyChanging();
					this._tenMonAn = value;
					this.SendPropertyChanged("tenMonAn");
					this.OntenMonAnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghiChu", DbType="NVarChar(500)")]
		public string ghiChu
		{
			get
			{
				return this._ghiChu;
			}
			set
			{
				if ((this._ghiChu != value))
				{
					this.OnghiChuChanging(value);
					this.SendPropertyChanging();
					this._ghiChu = value;
					this.SendPropertyChanged("ghiChu");
					this.OnghiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soLuongMonAn", DbType="Int")]
		public System.Nullable<int> soLuongMonAn
		{
			get
			{
				return this._soLuongMonAn;
			}
			set
			{
				if ((this._soLuongMonAn != value))
				{
					this.OnsoLuongMonAnChanging(value);
					this.SendPropertyChanging();
					this._soLuongMonAn = value;
					this.SendPropertyChanged("soLuongMonAn");
					this.OnsoLuongMonAnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayLap", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngayLap
		{
			get
			{
				return this._ngayLap;
			}
			set
			{
				if ((this._ngayLap != value))
				{
					this.OnngayLapChanging(value);
					this.SendPropertyChanging();
					this._ngayLap = value;
					this.SendPropertyChanged("ngayLap");
					this.OnngayLapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nguoiLap", DbType="VarChar(30)")]
		public string nguoiLap
		{
			get
			{
				return this._nguoiLap;
			}
			set
			{
				if ((this._nguoiLap != value))
				{
					this.OnnguoiLapChanging(value);
					this.SendPropertyChanging();
					this._nguoiLap = value;
					this.SendPropertyChanged("nguoiLap");
					this.OnnguoiLapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_avatar", DbType="NVarChar(500)")]
		public string avatar
		{
			get
			{
				return this._avatar;
			}
			set
			{
				if ((this._avatar != value))
				{
					this.OnavatarChanging(value);
					this.SendPropertyChanging();
					this._avatar = value;
					this.SendPropertyChanged("avatar");
					this.OnavatarChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_SA_NhanVienDangKySuatAnTrongThang")]
	public partial class tbl_SA_NhanVienDangKySuatAnTrongThang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _maNhanVien;
		
		private string _tenNhanVien;
		
		private string _tenPhongBan;
		
		private System.Nullable<int> _congChuan;
		
		private string _thuocCongTy;
		
		private System.Nullable<int> _thang;
		
		private System.Nullable<int> _nam;
		
		private System.Nullable<System.DateTime> _createDay;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnmaNhanVienChanging(string value);
    partial void OnmaNhanVienChanged();
    partial void OntenNhanVienChanging(string value);
    partial void OntenNhanVienChanged();
    partial void OntenPhongBanChanging(string value);
    partial void OntenPhongBanChanged();
    partial void OncongChuanChanging(System.Nullable<int> value);
    partial void OncongChuanChanged();
    partial void OnthuocCongTyChanging(string value);
    partial void OnthuocCongTyChanged();
    partial void OnthangChanging(System.Nullable<int> value);
    partial void OnthangChanged();
    partial void OnnamChanging(System.Nullable<int> value);
    partial void OnnamChanged();
    partial void OncreateDayChanging(System.Nullable<System.DateTime> value);
    partial void OncreateDayChanged();
    #endregion
		
		public tbl_SA_NhanVienDangKySuatAnTrongThang()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNhanVien", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string maNhanVien
		{
			get
			{
				return this._maNhanVien;
			}
			set
			{
				if ((this._maNhanVien != value))
				{
					this.OnmaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._maNhanVien = value;
					this.SendPropertyChanged("maNhanVien");
					this.OnmaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenNhanVien", DbType="NVarChar(100)")]
		public string tenNhanVien
		{
			get
			{
				return this._tenNhanVien;
			}
			set
			{
				if ((this._tenNhanVien != value))
				{
					this.OntenNhanVienChanging(value);
					this.SendPropertyChanging();
					this._tenNhanVien = value;
					this.SendPropertyChanged("tenNhanVien");
					this.OntenNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenPhongBan", DbType="NVarChar(200)")]
		public string tenPhongBan
		{
			get
			{
				return this._tenPhongBan;
			}
			set
			{
				if ((this._tenPhongBan != value))
				{
					this.OntenPhongBanChanging(value);
					this.SendPropertyChanging();
					this._tenPhongBan = value;
					this.SendPropertyChanged("tenPhongBan");
					this.OntenPhongBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_congChuan", DbType="Int")]
		public System.Nullable<int> congChuan
		{
			get
			{
				return this._congChuan;
			}
			set
			{
				if ((this._congChuan != value))
				{
					this.OncongChuanChanging(value);
					this.SendPropertyChanging();
					this._congChuan = value;
					this.SendPropertyChanged("congChuan");
					this.OncongChuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thuocCongTy", DbType="VarChar(30)")]
		public string thuocCongTy
		{
			get
			{
				return this._thuocCongTy;
			}
			set
			{
				if ((this._thuocCongTy != value))
				{
					this.OnthuocCongTyChanging(value);
					this.SendPropertyChanging();
					this._thuocCongTy = value;
					this.SendPropertyChanged("thuocCongTy");
					this.OnthuocCongTyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thang", DbType="Int")]
		public System.Nullable<int> thang
		{
			get
			{
				return this._thang;
			}
			set
			{
				if ((this._thang != value))
				{
					this.OnthangChanging(value);
					this.SendPropertyChanging();
					this._thang = value;
					this.SendPropertyChanged("thang");
					this.OnthangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nam", DbType="Int")]
		public System.Nullable<int> nam
		{
			get
			{
				return this._nam;
			}
			set
			{
				if ((this._nam != value))
				{
					this.OnnamChanging(value);
					this.SendPropertyChanging();
					this._nam = value;
					this.SendPropertyChanged("nam");
					this.OnnamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createDay", DbType="DateTime")]
		public System.Nullable<System.DateTime> createDay
		{
			get
			{
				return this._createDay;
			}
			set
			{
				if ((this._createDay != value))
				{
					this.OncreateDayChanging(value);
					this.SendPropertyChanging();
					this._createDay = value;
					this.SendPropertyChanged("createDay");
					this.OncreateDayChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_SA_CuaHang")]
	public partial class tbl_SA_CuaHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _maCuaHang;
		
		private string _tenCuaHang;
		
		private string _ghiChu;
		
		private System.Nullable<int> _soSuatAnTrongNgay;
		
		private System.Nullable<int> _suatAnTrenNhanVien;
		
		private System.Nullable<System.DateTime> _ngayLap;
		
		private string _nguoiLap;
		
		private System.Nullable<bool> _tinhTrangHetHieuLuc;
		
		private string _avatar;
		
		private string _email;
		
		private string _soDienThoai;
		
		private string _website;
		
		private bool _capQuanLy;
		
		private bool _lamTronLenTyLePhanBo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnmaCuaHangChanging(string value);
    partial void OnmaCuaHangChanged();
    partial void OntenCuaHangChanging(string value);
    partial void OntenCuaHangChanged();
    partial void OnghiChuChanging(string value);
    partial void OnghiChuChanged();
    partial void OnsoSuatAnTrongNgayChanging(System.Nullable<int> value);
    partial void OnsoSuatAnTrongNgayChanged();
    partial void OnsuatAnTrenNhanVienChanging(System.Nullable<int> value);
    partial void OnsuatAnTrenNhanVienChanged();
    partial void OnngayLapChanging(System.Nullable<System.DateTime> value);
    partial void OnngayLapChanged();
    partial void OnnguoiLapChanging(string value);
    partial void OnnguoiLapChanged();
    partial void OntinhTrangHetHieuLucChanging(System.Nullable<bool> value);
    partial void OntinhTrangHetHieuLucChanged();
    partial void OnavatarChanging(string value);
    partial void OnavatarChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnsoDienThoaiChanging(string value);
    partial void OnsoDienThoaiChanged();
    partial void OnwebsiteChanging(string value);
    partial void OnwebsiteChanged();
    partial void OncapQuanLyChanging(bool value);
    partial void OncapQuanLyChanged();
    partial void OnlamTronLenTyLePhanBoChanging(bool value);
    partial void OnlamTronLenTyLePhanBoChanged();
    #endregion
		
		public tbl_SA_CuaHang()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maCuaHang", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string maCuaHang
		{
			get
			{
				return this._maCuaHang;
			}
			set
			{
				if ((this._maCuaHang != value))
				{
					this.OnmaCuaHangChanging(value);
					this.SendPropertyChanging();
					this._maCuaHang = value;
					this.SendPropertyChanged("maCuaHang");
					this.OnmaCuaHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenCuaHang", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string tenCuaHang
		{
			get
			{
				return this._tenCuaHang;
			}
			set
			{
				if ((this._tenCuaHang != value))
				{
					this.OntenCuaHangChanging(value);
					this.SendPropertyChanging();
					this._tenCuaHang = value;
					this.SendPropertyChanged("tenCuaHang");
					this.OntenCuaHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghiChu", DbType="NVarChar(500)")]
		public string ghiChu
		{
			get
			{
				return this._ghiChu;
			}
			set
			{
				if ((this._ghiChu != value))
				{
					this.OnghiChuChanging(value);
					this.SendPropertyChanging();
					this._ghiChu = value;
					this.SendPropertyChanged("ghiChu");
					this.OnghiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soSuatAnTrongNgay", DbType="Int")]
		public System.Nullable<int> soSuatAnTrongNgay
		{
			get
			{
				return this._soSuatAnTrongNgay;
			}
			set
			{
				if ((this._soSuatAnTrongNgay != value))
				{
					this.OnsoSuatAnTrongNgayChanging(value);
					this.SendPropertyChanging();
					this._soSuatAnTrongNgay = value;
					this.SendPropertyChanged("soSuatAnTrongNgay");
					this.OnsoSuatAnTrongNgayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_suatAnTrenNhanVien", DbType="Int")]
		public System.Nullable<int> suatAnTrenNhanVien
		{
			get
			{
				return this._suatAnTrenNhanVien;
			}
			set
			{
				if ((this._suatAnTrenNhanVien != value))
				{
					this.OnsuatAnTrenNhanVienChanging(value);
					this.SendPropertyChanging();
					this._suatAnTrenNhanVien = value;
					this.SendPropertyChanged("suatAnTrenNhanVien");
					this.OnsuatAnTrenNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayLap", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngayLap
		{
			get
			{
				return this._ngayLap;
			}
			set
			{
				if ((this._ngayLap != value))
				{
					this.OnngayLapChanging(value);
					this.SendPropertyChanging();
					this._ngayLap = value;
					this.SendPropertyChanged("ngayLap");
					this.OnngayLapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nguoiLap", DbType="VarChar(30)")]
		public string nguoiLap
		{
			get
			{
				return this._nguoiLap;
			}
			set
			{
				if ((this._nguoiLap != value))
				{
					this.OnnguoiLapChanging(value);
					this.SendPropertyChanging();
					this._nguoiLap = value;
					this.SendPropertyChanged("nguoiLap");
					this.OnnguoiLapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tinhTrangHetHieuLuc", DbType="Bit")]
		public System.Nullable<bool> tinhTrangHetHieuLuc
		{
			get
			{
				return this._tinhTrangHetHieuLuc;
			}
			set
			{
				if ((this._tinhTrangHetHieuLuc != value))
				{
					this.OntinhTrangHetHieuLucChanging(value);
					this.SendPropertyChanging();
					this._tinhTrangHetHieuLuc = value;
					this.SendPropertyChanged("tinhTrangHetHieuLuc");
					this.OntinhTrangHetHieuLucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_avatar", DbType="NVarChar(500)")]
		public string avatar
		{
			get
			{
				return this._avatar;
			}
			set
			{
				if ((this._avatar != value))
				{
					this.OnavatarChanging(value);
					this.SendPropertyChanging();
					this._avatar = value;
					this.SendPropertyChanged("avatar");
					this.OnavatarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(100)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soDienThoai", DbType="VarChar(50)")]
		public string soDienThoai
		{
			get
			{
				return this._soDienThoai;
			}
			set
			{
				if ((this._soDienThoai != value))
				{
					this.OnsoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._soDienThoai = value;
					this.SendPropertyChanged("soDienThoai");
					this.OnsoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_website", DbType="NVarChar(100)")]
		public string website
		{
			get
			{
				return this._website;
			}
			set
			{
				if ((this._website != value))
				{
					this.OnwebsiteChanging(value);
					this.SendPropertyChanging();
					this._website = value;
					this.SendPropertyChanged("website");
					this.OnwebsiteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_capQuanLy", DbType="Bit NOT NULL")]
		public bool capQuanLy
		{
			get
			{
				return this._capQuanLy;
			}
			set
			{
				if ((this._capQuanLy != value))
				{
					this.OncapQuanLyChanging(value);
					this.SendPropertyChanging();
					this._capQuanLy = value;
					this.SendPropertyChanged("capQuanLy");
					this.OncapQuanLyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lamTronLenTyLePhanBo", DbType="Bit NOT NULL")]
		public bool lamTronLenTyLePhanBo
		{
			get
			{
				return this._lamTronLenTyLePhanBo;
			}
			set
			{
				if ((this._lamTronLenTyLePhanBo != value))
				{
					this.OnlamTronLenTyLePhanBoChanging(value);
					this.SendPropertyChanging();
					this._lamTronLenTyLePhanBo = value;
					this.SendPropertyChanged("lamTronLenTyLePhanBo");
					this.OnlamTronLenTyLePhanBoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_SA_DuyetPhanBo")]
	public partial class tbl_SA_DuyetPhanBo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _nam;
		
		private System.Nullable<int> _thang;
		
		private System.Nullable<System.DateTime> _createDay;
		
		private string _createUser;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnamChanging(System.Nullable<int> value);
    partial void OnnamChanged();
    partial void OnthangChanging(System.Nullable<int> value);
    partial void OnthangChanged();
    partial void OncreateDayChanging(System.Nullable<System.DateTime> value);
    partial void OncreateDayChanged();
    partial void OncreateUserChanging(string value);
    partial void OncreateUserChanged();
    #endregion
		
		public tbl_SA_DuyetPhanBo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nam", DbType="Int")]
		public System.Nullable<int> nam
		{
			get
			{
				return this._nam;
			}
			set
			{
				if ((this._nam != value))
				{
					this.OnnamChanging(value);
					this.SendPropertyChanging();
					this._nam = value;
					this.SendPropertyChanged("nam");
					this.OnnamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thang", DbType="Int")]
		public System.Nullable<int> thang
		{
			get
			{
				return this._thang;
			}
			set
			{
				if ((this._thang != value))
				{
					this.OnthangChanging(value);
					this.SendPropertyChanging();
					this._thang = value;
					this.SendPropertyChanged("thang");
					this.OnthangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createDay", DbType="DateTime")]
		public System.Nullable<System.DateTime> createDay
		{
			get
			{
				return this._createDay;
			}
			set
			{
				if ((this._createDay != value))
				{
					this.OncreateDayChanging(value);
					this.SendPropertyChanging();
					this._createDay = value;
					this.SendPropertyChanged("createDay");
					this.OncreateDayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createUser", DbType="VarChar(30)")]
		public string createUser
		{
			get
			{
				return this._createUser;
			}
			set
			{
				if ((this._createUser != value))
				{
					this.OncreateUserChanging(value);
					this.SendPropertyChanging();
					this._createUser = value;
					this.SendPropertyChanged("createUser");
					this.OncreateUserChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_SA_PhieuDangKySuatAn_LuuVet")]
	public partial class tbl_SA_PhieuDangKySuatAn_LuuVet : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _maCuaHang;
		
		private string _maCongTy;
		
		private string _maNhanVien;
		
		private string _tenNhanVien;
		
		private string _tenPhongBan;
		
		private System.DateTime _ngayDangKy;
		
		private string _ghiChu;
		
		private string _maMonAn;
		
		private string _thoiGianPhucVu;
		
		private System.Nullable<int> _sttPhucVu;
		
		private string _nguoiLap;
		
		private string _tenNguoiLap;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnmaCuaHangChanging(string value);
    partial void OnmaCuaHangChanged();
    partial void OnmaCongTyChanging(string value);
    partial void OnmaCongTyChanged();
    partial void OnmaNhanVienChanging(string value);
    partial void OnmaNhanVienChanged();
    partial void OntenNhanVienChanging(string value);
    partial void OntenNhanVienChanged();
    partial void OntenPhongBanChanging(string value);
    partial void OntenPhongBanChanged();
    partial void OnngayDangKyChanging(System.DateTime value);
    partial void OnngayDangKyChanged();
    partial void OnghiChuChanging(string value);
    partial void OnghiChuChanged();
    partial void OnmaMonAnChanging(string value);
    partial void OnmaMonAnChanged();
    partial void OnthoiGianPhucVuChanging(string value);
    partial void OnthoiGianPhucVuChanged();
    partial void OnsttPhucVuChanging(System.Nullable<int> value);
    partial void OnsttPhucVuChanged();
    partial void OnnguoiLapChanging(string value);
    partial void OnnguoiLapChanged();
    partial void OntenNguoiLapChanging(string value);
    partial void OntenNguoiLapChanged();
    #endregion
		
		public tbl_SA_PhieuDangKySuatAn_LuuVet()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maCuaHang", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string maCuaHang
		{
			get
			{
				return this._maCuaHang;
			}
			set
			{
				if ((this._maCuaHang != value))
				{
					this.OnmaCuaHangChanging(value);
					this.SendPropertyChanging();
					this._maCuaHang = value;
					this.SendPropertyChanged("maCuaHang");
					this.OnmaCuaHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maCongTy", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string maCongTy
		{
			get
			{
				return this._maCongTy;
			}
			set
			{
				if ((this._maCongTy != value))
				{
					this.OnmaCongTyChanging(value);
					this.SendPropertyChanging();
					this._maCongTy = value;
					this.SendPropertyChanged("maCongTy");
					this.OnmaCongTyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNhanVien", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string maNhanVien
		{
			get
			{
				return this._maNhanVien;
			}
			set
			{
				if ((this._maNhanVien != value))
				{
					this.OnmaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._maNhanVien = value;
					this.SendPropertyChanged("maNhanVien");
					this.OnmaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenNhanVien", DbType="NVarChar(200)")]
		public string tenNhanVien
		{
			get
			{
				return this._tenNhanVien;
			}
			set
			{
				if ((this._tenNhanVien != value))
				{
					this.OntenNhanVienChanging(value);
					this.SendPropertyChanging();
					this._tenNhanVien = value;
					this.SendPropertyChanged("tenNhanVien");
					this.OntenNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenPhongBan", DbType="NVarChar(200)")]
		public string tenPhongBan
		{
			get
			{
				return this._tenPhongBan;
			}
			set
			{
				if ((this._tenPhongBan != value))
				{
					this.OntenPhongBanChanging(value);
					this.SendPropertyChanging();
					this._tenPhongBan = value;
					this.SendPropertyChanged("tenPhongBan");
					this.OntenPhongBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayDangKy", DbType="DateTime NOT NULL")]
		public System.DateTime ngayDangKy
		{
			get
			{
				return this._ngayDangKy;
			}
			set
			{
				if ((this._ngayDangKy != value))
				{
					this.OnngayDangKyChanging(value);
					this.SendPropertyChanging();
					this._ngayDangKy = value;
					this.SendPropertyChanged("ngayDangKy");
					this.OnngayDangKyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghiChu", DbType="NVarChar(200)")]
		public string ghiChu
		{
			get
			{
				return this._ghiChu;
			}
			set
			{
				if ((this._ghiChu != value))
				{
					this.OnghiChuChanging(value);
					this.SendPropertyChanging();
					this._ghiChu = value;
					this.SendPropertyChanged("ghiChu");
					this.OnghiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maMonAn", DbType="VarChar(50)")]
		public string maMonAn
		{
			get
			{
				return this._maMonAn;
			}
			set
			{
				if ((this._maMonAn != value))
				{
					this.OnmaMonAnChanging(value);
					this.SendPropertyChanging();
					this._maMonAn = value;
					this.SendPropertyChanged("maMonAn");
					this.OnmaMonAnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thoiGianPhucVu", DbType="NVarChar(200)")]
		public string thoiGianPhucVu
		{
			get
			{
				return this._thoiGianPhucVu;
			}
			set
			{
				if ((this._thoiGianPhucVu != value))
				{
					this.OnthoiGianPhucVuChanging(value);
					this.SendPropertyChanging();
					this._thoiGianPhucVu = value;
					this.SendPropertyChanged("thoiGianPhucVu");
					this.OnthoiGianPhucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sttPhucVu", DbType="Int")]
		public System.Nullable<int> sttPhucVu
		{
			get
			{
				return this._sttPhucVu;
			}
			set
			{
				if ((this._sttPhucVu != value))
				{
					this.OnsttPhucVuChanging(value);
					this.SendPropertyChanging();
					this._sttPhucVu = value;
					this.SendPropertyChanged("sttPhucVu");
					this.OnsttPhucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nguoiLap", DbType="VarChar(50)")]
		public string nguoiLap
		{
			get
			{
				return this._nguoiLap;
			}
			set
			{
				if ((this._nguoiLap != value))
				{
					this.OnnguoiLapChanging(value);
					this.SendPropertyChanging();
					this._nguoiLap = value;
					this.SendPropertyChanged("nguoiLap");
					this.OnnguoiLapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenNguoiLap", DbType="NVarChar(100)")]
		public string tenNguoiLap
		{
			get
			{
				return this._tenNguoiLap;
			}
			set
			{
				if ((this._tenNguoiLap != value))
				{
					this.OntenNguoiLapChanging(value);
					this.SendPropertyChanging();
					this._tenNguoiLap = value;
					this.SendPropertyChanged("tenNguoiLap");
					this.OntenNguoiLapChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class sp_SA_PhanBoCuaHangCongChuan_IndexResult
	{
		
		private string _maCuaHang;
		
		private string _tenCuaHang;
		
		private System.Nullable<int> _soLanAnPhanBo;
		
		private System.Nullable<int> _congChuan;
		
		private System.Nullable<decimal> _tyLePhanBo;
		
		private System.Nullable<int> _soSuatAnNhanVienNhapTrongNgay;
		
		public sp_SA_PhanBoCuaHangCongChuan_IndexResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maCuaHang", DbType="VarChar(50)")]
		public string maCuaHang
		{
			get
			{
				return this._maCuaHang;
			}
			set
			{
				if ((this._maCuaHang != value))
				{
					this._maCuaHang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenCuaHang", DbType="NVarChar(200)")]
		public string tenCuaHang
		{
			get
			{
				return this._tenCuaHang;
			}
			set
			{
				if ((this._tenCuaHang != value))
				{
					this._tenCuaHang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soLanAnPhanBo", DbType="Int")]
		public System.Nullable<int> soLanAnPhanBo
		{
			get
			{
				return this._soLanAnPhanBo;
			}
			set
			{
				if ((this._soLanAnPhanBo != value))
				{
					this._soLanAnPhanBo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_congChuan", DbType="Int")]
		public System.Nullable<int> congChuan
		{
			get
			{
				return this._congChuan;
			}
			set
			{
				if ((this._congChuan != value))
				{
					this._congChuan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tyLePhanBo", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> tyLePhanBo
		{
			get
			{
				return this._tyLePhanBo;
			}
			set
			{
				if ((this._tyLePhanBo != value))
				{
					this._tyLePhanBo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soSuatAnNhanVienNhapTrongNgay", DbType="Int")]
		public System.Nullable<int> soSuatAnNhanVienNhapTrongNgay
		{
			get
			{
				return this._soSuatAnNhanVienNhapTrongNgay;
			}
			set
			{
				if ((this._soSuatAnNhanVienNhapTrongNgay != value))
				{
					this._soSuatAnNhanVienNhapTrongNgay = value;
				}
			}
		}
	}
	
	public partial class sp_CuaHang_MonAn_NhanVien_IndexResult
	{
		
		private string _maCuaHang;
		
		private string _tenCuaHang;
		
		private string _maNhanVien;
		
		private string _tenNhanVien;
		
		private string _tenPhongBan;
		
		private string _maMonAn;
		
		private string _tenMonAn;
		
		private System.Nullable<System.DateTime> _gioDangKy;
		
		private string _thoiGianPhucVu;
		
		private string _tenCongTy;
		
		private System.Nullable<int> _sttPhucVu;
		
		public sp_CuaHang_MonAn_NhanVien_IndexResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maCuaHang", DbType="VarChar(50)")]
		public string maCuaHang
		{
			get
			{
				return this._maCuaHang;
			}
			set
			{
				if ((this._maCuaHang != value))
				{
					this._maCuaHang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenCuaHang", DbType="NVarChar(200)")]
		public string tenCuaHang
		{
			get
			{
				return this._tenCuaHang;
			}
			set
			{
				if ((this._tenCuaHang != value))
				{
					this._tenCuaHang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNhanVien", DbType="VarChar(50)")]
		public string maNhanVien
		{
			get
			{
				return this._maNhanVien;
			}
			set
			{
				if ((this._maNhanVien != value))
				{
					this._maNhanVien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenNhanVien", DbType="NVarChar(200)")]
		public string tenNhanVien
		{
			get
			{
				return this._tenNhanVien;
			}
			set
			{
				if ((this._tenNhanVien != value))
				{
					this._tenNhanVien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenPhongBan", DbType="NVarChar(200)")]
		public string tenPhongBan
		{
			get
			{
				return this._tenPhongBan;
			}
			set
			{
				if ((this._tenPhongBan != value))
				{
					this._tenPhongBan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maMonAn", DbType="VarChar(50)")]
		public string maMonAn
		{
			get
			{
				return this._maMonAn;
			}
			set
			{
				if ((this._maMonAn != value))
				{
					this._maMonAn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenMonAn", DbType="NVarChar(200)")]
		public string tenMonAn
		{
			get
			{
				return this._tenMonAn;
			}
			set
			{
				if ((this._tenMonAn != value))
				{
					this._tenMonAn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioDangKy", DbType="DateTime")]
		public System.Nullable<System.DateTime> gioDangKy
		{
			get
			{
				return this._gioDangKy;
			}
			set
			{
				if ((this._gioDangKy != value))
				{
					this._gioDangKy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thoiGianPhucVu", DbType="NVarChar(200)")]
		public string thoiGianPhucVu
		{
			get
			{
				return this._thoiGianPhucVu;
			}
			set
			{
				if ((this._thoiGianPhucVu != value))
				{
					this._thoiGianPhucVu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenCongTy", DbType="NVarChar(200)")]
		public string tenCongTy
		{
			get
			{
				return this._tenCongTy;
			}
			set
			{
				if ((this._tenCongTy != value))
				{
					this._tenCongTy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sttPhucVu", DbType="Int")]
		public System.Nullable<int> sttPhucVu
		{
			get
			{
				return this._sttPhucVu;
			}
			set
			{
				if ((this._sttPhucVu != value))
				{
					this._sttPhucVu = value;
				}
			}
		}
	}
	
	public partial class sp_SA_NhanVienDangKySuatAnTrongThang_IndexResult
	{
		
		private System.Nullable<int> _congChuan;
		
		private string _maCuaHang;
		
		private string _tenCuaHang;
		
		private System.Nullable<int> _soLanAn;
		
		public sp_SA_NhanVienDangKySuatAnTrongThang_IndexResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_congChuan", DbType="Int")]
		public System.Nullable<int> congChuan
		{
			get
			{
				return this._congChuan;
			}
			set
			{
				if ((this._congChuan != value))
				{
					this._congChuan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maCuaHang", DbType="VarChar(30)")]
		public string maCuaHang
		{
			get
			{
				return this._maCuaHang;
			}
			set
			{
				if ((this._maCuaHang != value))
				{
					this._maCuaHang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenCuaHang", DbType="NVarChar(200)")]
		public string tenCuaHang
		{
			get
			{
				return this._tenCuaHang;
			}
			set
			{
				if ((this._tenCuaHang != value))
				{
					this._tenCuaHang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soLanAn", DbType="Int")]
		public System.Nullable<int> soLanAn
		{
			get
			{
				return this._soLanAn;
			}
			set
			{
				if ((this._soLanAn != value))
				{
					this._soLanAn = value;
				}
			}
		}
	}
	
	public partial class sp_SA_BC_ThongKeSuatAnTheoTungCuaHangResult
	{
		
		private string _maCuaHang;
		
		private string _tenCuaHang;
		
		private string _ghiChu;
		
		private System.Nullable<int> _soSuatAnPhanBoTrongThang;
		
		private System.Nullable<int> _tongNhanVienDangKyTrongThang;
		
		private System.Nullable<int> _tongNgayCongTheoCongChuanTrongThang;
		
		private System.Nullable<decimal> _tyLePhanBo;
		
		private System.Nullable<int> _soSuatAnNhapVaoTungCuaHang;
		
		private System.Nullable<int> _tongSoSuatAnTatCaCuaHang;
		
		private System.Nullable<int> _ngayCongChuanTrungBinhTrongThang;
		
		private System.Nullable<int> _soSuatAnPhanBoDapUngToiDaTrongNgay;
		
		public sp_SA_BC_ThongKeSuatAnTheoTungCuaHangResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maCuaHang", DbType="VarChar(30)")]
		public string maCuaHang
		{
			get
			{
				return this._maCuaHang;
			}
			set
			{
				if ((this._maCuaHang != value))
				{
					this._maCuaHang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenCuaHang", DbType="NVarChar(200)")]
		public string tenCuaHang
		{
			get
			{
				return this._tenCuaHang;
			}
			set
			{
				if ((this._tenCuaHang != value))
				{
					this._tenCuaHang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghiChu", DbType="NVarChar(200)")]
		public string ghiChu
		{
			get
			{
				return this._ghiChu;
			}
			set
			{
				if ((this._ghiChu != value))
				{
					this._ghiChu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soSuatAnPhanBoTrongThang", DbType="Int")]
		public System.Nullable<int> soSuatAnPhanBoTrongThang
		{
			get
			{
				return this._soSuatAnPhanBoTrongThang;
			}
			set
			{
				if ((this._soSuatAnPhanBoTrongThang != value))
				{
					this._soSuatAnPhanBoTrongThang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongNhanVienDangKyTrongThang", DbType="Int")]
		public System.Nullable<int> tongNhanVienDangKyTrongThang
		{
			get
			{
				return this._tongNhanVienDangKyTrongThang;
			}
			set
			{
				if ((this._tongNhanVienDangKyTrongThang != value))
				{
					this._tongNhanVienDangKyTrongThang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongNgayCongTheoCongChuanTrongThang", DbType="Int")]
		public System.Nullable<int> tongNgayCongTheoCongChuanTrongThang
		{
			get
			{
				return this._tongNgayCongTheoCongChuanTrongThang;
			}
			set
			{
				if ((this._tongNgayCongTheoCongChuanTrongThang != value))
				{
					this._tongNgayCongTheoCongChuanTrongThang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tyLePhanBo", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> tyLePhanBo
		{
			get
			{
				return this._tyLePhanBo;
			}
			set
			{
				if ((this._tyLePhanBo != value))
				{
					this._tyLePhanBo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soSuatAnNhapVaoTungCuaHang", DbType="Int")]
		public System.Nullable<int> soSuatAnNhapVaoTungCuaHang
		{
			get
			{
				return this._soSuatAnNhapVaoTungCuaHang;
			}
			set
			{
				if ((this._soSuatAnNhapVaoTungCuaHang != value))
				{
					this._soSuatAnNhapVaoTungCuaHang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongSoSuatAnTatCaCuaHang", DbType="Int")]
		public System.Nullable<int> tongSoSuatAnTatCaCuaHang
		{
			get
			{
				return this._tongSoSuatAnTatCaCuaHang;
			}
			set
			{
				if ((this._tongSoSuatAnTatCaCuaHang != value))
				{
					this._tongSoSuatAnTatCaCuaHang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayCongChuanTrungBinhTrongThang", DbType="Int")]
		public System.Nullable<int> ngayCongChuanTrungBinhTrongThang
		{
			get
			{
				return this._ngayCongChuanTrungBinhTrongThang;
			}
			set
			{
				if ((this._ngayCongChuanTrungBinhTrongThang != value))
				{
					this._ngayCongChuanTrungBinhTrongThang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soSuatAnPhanBoDapUngToiDaTrongNgay", DbType="Int")]
		public System.Nullable<int> soSuatAnPhanBoDapUngToiDaTrongNgay
		{
			get
			{
				return this._soSuatAnPhanBoDapUngToiDaTrongNgay;
			}
			set
			{
				if ((this._soSuatAnPhanBoDapUngToiDaTrongNgay != value))
				{
					this._soSuatAnPhanBoDapUngToiDaTrongNgay = value;
				}
			}
		}
	}
	
	public partial class sp_SA_BC_ThongKeSuatAnTungNhanVienResult
	{
		
		private string _maNhanVien;
		
		private string _tenNhanVien;
		
		private string _tenPhongBan;
		
		private System.Nullable<int> _soPhieuDangKyTuNgayDenNgay;
		
		private string _maCongTy;
		
		private string _maCuaHang;
		
		private string _tenCuaHang;
		
		private System.Nullable<long> _soDong;
		
		private System.Nullable<int> _tongSoDong;
		
		public sp_SA_BC_ThongKeSuatAnTungNhanVienResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNhanVien", DbType="VarChar(30)")]
		public string maNhanVien
		{
			get
			{
				return this._maNhanVien;
			}
			set
			{
				if ((this._maNhanVien != value))
				{
					this._maNhanVien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenNhanVien", DbType="NVarChar(100)")]
		public string tenNhanVien
		{
			get
			{
				return this._tenNhanVien;
			}
			set
			{
				if ((this._tenNhanVien != value))
				{
					this._tenNhanVien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenPhongBan", DbType="NVarChar(200)")]
		public string tenPhongBan
		{
			get
			{
				return this._tenPhongBan;
			}
			set
			{
				if ((this._tenPhongBan != value))
				{
					this._tenPhongBan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soPhieuDangKyTuNgayDenNgay", DbType="Int")]
		public System.Nullable<int> soPhieuDangKyTuNgayDenNgay
		{
			get
			{
				return this._soPhieuDangKyTuNgayDenNgay;
			}
			set
			{
				if ((this._soPhieuDangKyTuNgayDenNgay != value))
				{
					this._soPhieuDangKyTuNgayDenNgay = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maCongTy", DbType="VarChar(30)")]
		public string maCongTy
		{
			get
			{
				return this._maCongTy;
			}
			set
			{
				if ((this._maCongTy != value))
				{
					this._maCongTy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maCuaHang", DbType="VarChar(30)")]
		public string maCuaHang
		{
			get
			{
				return this._maCuaHang;
			}
			set
			{
				if ((this._maCuaHang != value))
				{
					this._maCuaHang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenCuaHang", DbType="NVarChar(200)")]
		public string tenCuaHang
		{
			get
			{
				return this._tenCuaHang;
			}
			set
			{
				if ((this._tenCuaHang != value))
				{
					this._tenCuaHang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soDong", DbType="BigInt")]
		public System.Nullable<long> soDong
		{
			get
			{
				return this._soDong;
			}
			set
			{
				if ((this._soDong != value))
				{
					this._soDong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongSoDong", DbType="Int")]
		public System.Nullable<int> tongSoDong
		{
			get
			{
				return this._tongSoDong;
			}
			set
			{
				if ((this._tongSoDong != value))
				{
					this._tongSoDong = value;
				}
			}
		}
	}
	
	public partial class sp_SA_PhieuDangKySuatAn_CuaHang_LuuVet_PhanBoResult
	{
		
		private string _maCuaHang;
		
		private string _tenCuaHang;
		
		private string _moTa;
		
		private string _hinhAnh;
		
		private System.Nullable<int> _soSuatAnTrongNgayDaDangKyCH;
		
		private System.Nullable<int> _soLanAnCuaNhanVienTrongThang;
		
		private System.Nullable<int> _soLanNhanVienDuocDangKyTrongThang;
		
		private System.Nullable<int> _soLanNhanVienDaDangKy;
		
		private System.Nullable<int> _tongSoSuatCuaCuaHangTrongNgay;
		
		private System.Nullable<int> _tongSoSuatConLaiCuaCuaHangTrongNgay;
		
		private System.Nullable<int> _tongSoSuatDaDangKyCuaCuaHangTrongNgay;
		
		private System.Nullable<bool> _tinhTrangHetHieuLuc;
		
		public sp_SA_PhieuDangKySuatAn_CuaHang_LuuVet_PhanBoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maCuaHang", DbType="VarChar(50)")]
		public string maCuaHang
		{
			get
			{
				return this._maCuaHang;
			}
			set
			{
				if ((this._maCuaHang != value))
				{
					this._maCuaHang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenCuaHang", DbType="NVarChar(200)")]
		public string tenCuaHang
		{
			get
			{
				return this._tenCuaHang;
			}
			set
			{
				if ((this._tenCuaHang != value))
				{
					this._tenCuaHang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_moTa", DbType="NVarChar(200)")]
		public string moTa
		{
			get
			{
				return this._moTa;
			}
			set
			{
				if ((this._moTa != value))
				{
					this._moTa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hinhAnh", DbType="NVarChar(200)")]
		public string hinhAnh
		{
			get
			{
				return this._hinhAnh;
			}
			set
			{
				if ((this._hinhAnh != value))
				{
					this._hinhAnh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soSuatAnTrongNgayDaDangKyCH", DbType="Int")]
		public System.Nullable<int> soSuatAnTrongNgayDaDangKyCH
		{
			get
			{
				return this._soSuatAnTrongNgayDaDangKyCH;
			}
			set
			{
				if ((this._soSuatAnTrongNgayDaDangKyCH != value))
				{
					this._soSuatAnTrongNgayDaDangKyCH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soLanAnCuaNhanVienTrongThang", DbType="Int")]
		public System.Nullable<int> soLanAnCuaNhanVienTrongThang
		{
			get
			{
				return this._soLanAnCuaNhanVienTrongThang;
			}
			set
			{
				if ((this._soLanAnCuaNhanVienTrongThang != value))
				{
					this._soLanAnCuaNhanVienTrongThang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soLanNhanVienDuocDangKyTrongThang", DbType="Int")]
		public System.Nullable<int> soLanNhanVienDuocDangKyTrongThang
		{
			get
			{
				return this._soLanNhanVienDuocDangKyTrongThang;
			}
			set
			{
				if ((this._soLanNhanVienDuocDangKyTrongThang != value))
				{
					this._soLanNhanVienDuocDangKyTrongThang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soLanNhanVienDaDangKy", DbType="Int")]
		public System.Nullable<int> soLanNhanVienDaDangKy
		{
			get
			{
				return this._soLanNhanVienDaDangKy;
			}
			set
			{
				if ((this._soLanNhanVienDaDangKy != value))
				{
					this._soLanNhanVienDaDangKy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongSoSuatCuaCuaHangTrongNgay", DbType="Int")]
		public System.Nullable<int> tongSoSuatCuaCuaHangTrongNgay
		{
			get
			{
				return this._tongSoSuatCuaCuaHangTrongNgay;
			}
			set
			{
				if ((this._tongSoSuatCuaCuaHangTrongNgay != value))
				{
					this._tongSoSuatCuaCuaHangTrongNgay = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongSoSuatConLaiCuaCuaHangTrongNgay", DbType="Int")]
		public System.Nullable<int> tongSoSuatConLaiCuaCuaHangTrongNgay
		{
			get
			{
				return this._tongSoSuatConLaiCuaCuaHangTrongNgay;
			}
			set
			{
				if ((this._tongSoSuatConLaiCuaCuaHangTrongNgay != value))
				{
					this._tongSoSuatConLaiCuaCuaHangTrongNgay = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongSoSuatDaDangKyCuaCuaHangTrongNgay", DbType="Int")]
		public System.Nullable<int> tongSoSuatDaDangKyCuaCuaHangTrongNgay
		{
			get
			{
				return this._tongSoSuatDaDangKyCuaCuaHangTrongNgay;
			}
			set
			{
				if ((this._tongSoSuatDaDangKyCuaCuaHangTrongNgay != value))
				{
					this._tongSoSuatDaDangKyCuaCuaHangTrongNgay = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tinhTrangHetHieuLuc", DbType="Bit")]
		public System.Nullable<bool> tinhTrangHetHieuLuc
		{
			get
			{
				return this._tinhTrangHetHieuLuc;
			}
			set
			{
				if ((this._tinhTrangHetHieuLuc != value))
				{
					this._tinhTrangHetHieuLuc = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
