#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatDongSan.Models.ERP
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HT_DMSTVWindow")]
	public partial class ERPTVDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_DMS_NhanVienHR(tbl_DMS_NhanVienHR instance);
    partial void Updatetbl_DMS_NhanVienHR(tbl_DMS_NhanVienHR instance);
    partial void Deletetbl_DMS_NhanVienHR(tbl_DMS_NhanVienHR instance);
    partial void Inserttbl_DMS_PhongBan(tbl_DMS_PhongBan instance);
    partial void Updatetbl_DMS_PhongBan(tbl_DMS_PhongBan instance);
    partial void Deletetbl_DMS_PhongBan(tbl_DMS_PhongBan instance);
    #endregion
		
		public ERPTVDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ERPTVDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ERPTVDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ERPTVDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_DMS_NhanVienHR> tbl_DMS_NhanVienHRs
		{
			get
			{
				return this.GetTable<tbl_DMS_NhanVienHR>();
			}
		}
		
		public System.Data.Linq.Table<tbl_DMS_PhongBan> tbl_DMS_PhongBans
		{
			get
			{
				return this.GetTable<tbl_DMS_PhongBan>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_DMS_NhanVienHR")]
	public partial class tbl_DMS_NhanVienHR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _userName;
		
		private string _matKhau;
		
		private string _email;
		
		private string _soDienThoai;
		
		private string _hoTen;
		
		private string _maPhongBan;
		
		private System.Nullable<int> _soCapBac;
		
		private string _tenCapBac;
		
		private System.Nullable<System.DateTime> _ngaySinh;
		
		private string _tenChucDanh;
		
		private System.Nullable<int> _trangThai;
		
		private string _maNhanVien;
		
		private string _maCongTrinh;
		
		private string _maChucDanh;
		
		private System.Nullable<double> _dungLuong;
		
		private System.Nullable<int> _nvDMS;
		
		private System.Nullable<bool> _choPhepVaoERPKhac;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuserNameChanging(string value);
    partial void OnuserNameChanged();
    partial void OnmatKhauChanging(string value);
    partial void OnmatKhauChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnsoDienThoaiChanging(string value);
    partial void OnsoDienThoaiChanged();
    partial void OnhoTenChanging(string value);
    partial void OnhoTenChanged();
    partial void OnmaPhongBanChanging(string value);
    partial void OnmaPhongBanChanged();
    partial void OnsoCapBacChanging(System.Nullable<int> value);
    partial void OnsoCapBacChanged();
    partial void OntenCapBacChanging(string value);
    partial void OntenCapBacChanged();
    partial void OnngaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnngaySinhChanged();
    partial void OntenChucDanhChanging(string value);
    partial void OntenChucDanhChanged();
    partial void OntrangThaiChanging(System.Nullable<int> value);
    partial void OntrangThaiChanged();
    partial void OnmaNhanVienChanging(string value);
    partial void OnmaNhanVienChanged();
    partial void OnmaCongTrinhChanging(string value);
    partial void OnmaCongTrinhChanged();
    partial void OnmaChucDanhChanging(string value);
    partial void OnmaChucDanhChanged();
    partial void OndungLuongChanging(System.Nullable<double> value);
    partial void OndungLuongChanged();
    partial void OnnvDMSChanging(System.Nullable<int> value);
    partial void OnnvDMSChanged();
    partial void OnchoPhepVaoERPKhacChanging(System.Nullable<bool> value);
    partial void OnchoPhepVaoERPKhacChanged();
    #endregion
		
		public tbl_DMS_NhanVienHR()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userName", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string userName
		{
			get
			{
				return this._userName;
			}
			set
			{
				if ((this._userName != value))
				{
					this.OnuserNameChanging(value);
					this.SendPropertyChanging();
					this._userName = value;
					this.SendPropertyChanged("userName");
					this.OnuserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matKhau", DbType="NVarChar(500)")]
		public string matKhau
		{
			get
			{
				return this._matKhau;
			}
			set
			{
				if ((this._matKhau != value))
				{
					this.OnmatKhauChanging(value);
					this.SendPropertyChanging();
					this._matKhau = value;
					this.SendPropertyChanged("matKhau");
					this.OnmatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(150)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soDienThoai", DbType="NVarChar(50)")]
		public string soDienThoai
		{
			get
			{
				return this._soDienThoai;
			}
			set
			{
				if ((this._soDienThoai != value))
				{
					this.OnsoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._soDienThoai = value;
					this.SendPropertyChanged("soDienThoai");
					this.OnsoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoTen", DbType="NVarChar(150)")]
		public string hoTen
		{
			get
			{
				return this._hoTen;
			}
			set
			{
				if ((this._hoTen != value))
				{
					this.OnhoTenChanging(value);
					this.SendPropertyChanging();
					this._hoTen = value;
					this.SendPropertyChanged("hoTen");
					this.OnhoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maPhongBan", DbType="VarChar(150)")]
		public string maPhongBan
		{
			get
			{
				return this._maPhongBan;
			}
			set
			{
				if ((this._maPhongBan != value))
				{
					this.OnmaPhongBanChanging(value);
					this.SendPropertyChanging();
					this._maPhongBan = value;
					this.SendPropertyChanged("maPhongBan");
					this.OnmaPhongBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soCapBac", DbType="Int")]
		public System.Nullable<int> soCapBac
		{
			get
			{
				return this._soCapBac;
			}
			set
			{
				if ((this._soCapBac != value))
				{
					this.OnsoCapBacChanging(value);
					this.SendPropertyChanging();
					this._soCapBac = value;
					this.SendPropertyChanged("soCapBac");
					this.OnsoCapBacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenCapBac", DbType="NVarChar(150)")]
		public string tenCapBac
		{
			get
			{
				return this._tenCapBac;
			}
			set
			{
				if ((this._tenCapBac != value))
				{
					this.OntenCapBacChanging(value);
					this.SendPropertyChanging();
					this._tenCapBac = value;
					this.SendPropertyChanged("tenCapBac");
					this.OntenCapBacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> ngaySinh
		{
			get
			{
				return this._ngaySinh;
			}
			set
			{
				if ((this._ngaySinh != value))
				{
					this.OnngaySinhChanging(value);
					this.SendPropertyChanging();
					this._ngaySinh = value;
					this.SendPropertyChanged("ngaySinh");
					this.OnngaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenChucDanh", DbType="NVarChar(250)")]
		public string tenChucDanh
		{
			get
			{
				return this._tenChucDanh;
			}
			set
			{
				if ((this._tenChucDanh != value))
				{
					this.OntenChucDanhChanging(value);
					this.SendPropertyChanging();
					this._tenChucDanh = value;
					this.SendPropertyChanged("tenChucDanh");
					this.OntenChucDanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangThai", DbType="Int")]
		public System.Nullable<int> trangThai
		{
			get
			{
				return this._trangThai;
			}
			set
			{
				if ((this._trangThai != value))
				{
					this.OntrangThaiChanging(value);
					this.SendPropertyChanging();
					this._trangThai = value;
					this.SendPropertyChanged("trangThai");
					this.OntrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNhanVien", DbType="VarChar(50)")]
		public string maNhanVien
		{
			get
			{
				return this._maNhanVien;
			}
			set
			{
				if ((this._maNhanVien != value))
				{
					this.OnmaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._maNhanVien = value;
					this.SendPropertyChanged("maNhanVien");
					this.OnmaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maCongTrinh", DbType="VarChar(50)")]
		public string maCongTrinh
		{
			get
			{
				return this._maCongTrinh;
			}
			set
			{
				if ((this._maCongTrinh != value))
				{
					this.OnmaCongTrinhChanging(value);
					this.SendPropertyChanging();
					this._maCongTrinh = value;
					this.SendPropertyChanged("maCongTrinh");
					this.OnmaCongTrinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maChucDanh", DbType="NVarChar(50)")]
		public string maChucDanh
		{
			get
			{
				return this._maChucDanh;
			}
			set
			{
				if ((this._maChucDanh != value))
				{
					this.OnmaChucDanhChanging(value);
					this.SendPropertyChanging();
					this._maChucDanh = value;
					this.SendPropertyChanged("maChucDanh");
					this.OnmaChucDanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dungLuong", DbType="Float")]
		public System.Nullable<double> dungLuong
		{
			get
			{
				return this._dungLuong;
			}
			set
			{
				if ((this._dungLuong != value))
				{
					this.OndungLuongChanging(value);
					this.SendPropertyChanging();
					this._dungLuong = value;
					this.SendPropertyChanged("dungLuong");
					this.OndungLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvDMS", DbType="Int")]
		public System.Nullable<int> nvDMS
		{
			get
			{
				return this._nvDMS;
			}
			set
			{
				if ((this._nvDMS != value))
				{
					this.OnnvDMSChanging(value);
					this.SendPropertyChanging();
					this._nvDMS = value;
					this.SendPropertyChanged("nvDMS");
					this.OnnvDMSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_choPhepVaoERPKhac", DbType="Bit")]
		public System.Nullable<bool> choPhepVaoERPKhac
		{
			get
			{
				return this._choPhepVaoERPKhac;
			}
			set
			{
				if ((this._choPhepVaoERPKhac != value))
				{
					this.OnchoPhepVaoERPKhacChanging(value);
					this.SendPropertyChanging();
					this._choPhepVaoERPKhac = value;
					this.SendPropertyChanged("choPhepVaoERPKhac");
					this.OnchoPhepVaoERPKhacChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_DMS_PhongBan")]
	public partial class tbl_DMS_PhongBan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maPhongBan;
		
		private string _tenPhongBan;
		
		private string _maCha;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaPhongBanChanging(string value);
    partial void OnmaPhongBanChanged();
    partial void OntenPhongBanChanging(string value);
    partial void OntenPhongBanChanged();
    partial void OnmaChaChanging(string value);
    partial void OnmaChaChanged();
    #endregion
		
		public tbl_DMS_PhongBan()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maPhongBan", DbType="NVarChar(150) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maPhongBan
		{
			get
			{
				return this._maPhongBan;
			}
			set
			{
				if ((this._maPhongBan != value))
				{
					this.OnmaPhongBanChanging(value);
					this.SendPropertyChanging();
					this._maPhongBan = value;
					this.SendPropertyChanged("maPhongBan");
					this.OnmaPhongBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenPhongBan", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string tenPhongBan
		{
			get
			{
				return this._tenPhongBan;
			}
			set
			{
				if ((this._tenPhongBan != value))
				{
					this.OntenPhongBanChanging(value);
					this.SendPropertyChanging();
					this._tenPhongBan = value;
					this.SendPropertyChanged("tenPhongBan");
					this.OntenPhongBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maCha", DbType="NVarChar(150)")]
		public string maCha
		{
			get
			{
				return this._maCha;
			}
			set
			{
				if ((this._maCha != value))
				{
					this.OnmaChaChanging(value);
					this.SendPropertyChanging();
					this._maCha = value;
					this.SendPropertyChanged("maCha");
					this.OnmaChaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
