<?xml version="1.0" encoding="utf-8"?><Database Name="HT_DMSTVWindow" Class="ERPTVDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.tbl_DMS_NhanVienHR" Member="tbl_DMS_NhanVienHRs">
    <Type Name="tbl_DMS_NhanVienHR">
      <Column Name="userName" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="matKhau" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="soDienThoai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="hoTen" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="maPhongBan" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="soCapBac" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tenCapBac" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="ngaySinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="tenChucDanh" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="trangThai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="maNhanVien" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="maCongTrinh" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="maChucDanh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="dungLuong" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="nvDMS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="choPhepVaoERPKhac" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_DMS_PhongBan" Member="tbl_DMS_PhongBans">
    <Type Name="tbl_DMS_PhongBan">
      <Column Name="maPhongBan" Type="System.String" DbType="NVarChar(150) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenPhongBan" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="maCha" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
    </Type>
  </Table>
</Database>